import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, LayoutDashboard, Pencil, Plus, Save } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { useWorkspace } from "@/auth/WorkspaceContext";
import * as dashboardsApi from "@/api/dashboards";
import * as analyticsApi from "@/api/analytics";
import * as eventsApi from "@/api/events";
import * as funnelsApi from "@/api/funnels";
import * as pagesApi from "@/api/pages";
import * as segmentsApi from "@/api/segments";
import { PageHeader } from "@/components/PageHeader";
import { EmptyState } from "@/components/EmptyState";
import { ErrorNotice, LoadingRows } from "@/components/PageSurface";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { CardEditorDialog } from "@/components/dashboard/CardEditorDialog";
import { DashboardCardView } from "@/components/dashboard/DashboardCardView";
import { DashboardFilterBar, defaultDashboardFilters } from "@/components/dashboard/DashboardFilterBar";
import type { AnalyticsCatalog, AnalyticsResponse, DashboardCard, DashboardFilters, EventDefinitionSummary, FunnelListItem, Segment } from "@/types/api";

export function DashboardWorkspacePage({ mode }: { mode: "new" | "view" | "edit" }) {
  const { dashboardId } = useParams(); const navigate = useNavigate(); const { currentOrg, currentSite, loading: workspaceLoading } = useWorkspace(); const canMutate = currentOrg?.role === "ADMIN" || currentOrg?.role === "OWNER"; const editable = mode !== "view" && canMutate;
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [cards, setCards] = useState<DashboardCard[]>([]); const [filters, setFilters] = useState<DashboardFilters>(defaultDashboardFilters); const [catalog, setCatalog] = useState<AnalyticsCatalog>(); const [events, setEvents] = useState<EventDefinitionSummary[]>([]); const [funnels, setFunnels] = useState<FunnelListItem[]>([]); const [segments, setSegments] = useState<Segment[]>([]); const [results, setResults] = useState<Record<string, AnalyticsResponse>>({}); const [errors, setErrors] = useState<Record<string, string>>({}); const [loading, setLoading] = useState(mode !== "new"); const [pageError, setPageError] = useState<string>(); const [dirty, setDirty] = useState(false); const [editingIndex, setEditingIndex] = useState<number | "new" | null>(null); const [saving, setSaving] = useState(false);
  const [details, setDetails] = useState<{ kind: string; items: Record<string, unknown>[]; total: number }>(); const [draggingIndex, setDraggingIndex] = useState<number | null>(null);
  const [editingName, setEditingName] = useState(false); const [editingDescription, setEditingDescription] = useState(false);
  const nameInputRef = useRef<HTMLInputElement>(null); const descriptionInputRef = useRef<HTMLTextAreaElement>(null);
  useEffect(() => { if (editingName) nameInputRef.current?.select(); }, [editingName]);
  useEffect(() => { if (editingDescription) descriptionInputRef.current?.select(); }, [editingDescription]);
  useEffect(() => { const handler = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; window.addEventListener("beforeunload", handler); return () => window.removeEventListener("beforeunload", handler); }, [dirty]);
  useEffect(() => { if (!currentOrg || !currentSite) return; Promise.all([analyticsApi.getCatalog(currentOrg.orgId, currentSite.id), eventsApi.listEvents(currentOrg.orgId, currentSite.id, { limit: 100 }), funnelsApi.listFunnels(currentOrg.orgId, currentSite.id, { limit: 100 }), segmentsApi.listSegments(currentOrg.orgId, currentSite.id, { limit: 100 }), pagesApi.listPages(currentOrg.orgId, currentSite.id)]).then(([c, e, f, s]) => { setCatalog(c); setEvents(e.events); setFunnels(f.funnels); setSegments(s.segments); }).catch(() => setPageError("Could not load analytics selectors.")); }, [currentOrg, currentSite]);
  useEffect(() => { if (mode === "new") { setLoading(false); return; } if (!currentOrg || !currentSite || !dashboardId) return; setLoading(true); dashboardsApi.getDashboard(currentOrg.orgId, currentSite.id, dashboardId).then((d) => { setName(d.name); setDescription(d.description ?? ""); setCards(d.cards); setDirty(false); }).catch((e) => setPageError(e instanceof Error ? e.message : "Could not load dashboard.")).finally(() => setLoading(false)); }, [mode, currentOrg, currentSite, dashboardId]);
  const queryKey = useMemo(() => JSON.stringify({ filters, queries: cards.map((card) => ({ id: card.id ?? `${card.title}-${card.position}`, query: semanticQuery(card) })) }), [filters, cards]);
  const refresh = useCallback(() => { if (!currentOrg || !currentSite || !cards.length) { setResults({}); return; } const queries = cards.map((card, index) => ({ requestId: cardKey(card, index), query: card.configuration })); setErrors({}); analyticsApi.queryAnalyticsBatch(currentOrg.orgId, currentSite.id, filters, queries).then(({ results: batch }) => { const next: Record<string, AnalyticsResponse> = {}, nextErrors: Record<string, string> = {}; for (const item of batch) item.status === "ok" ? next[item.requestId] = item : nextErrors[item.requestId] = item.message; setResults(next); setErrors(nextErrors); }).catch((e) => setPageError(e instanceof Error ? e.message : "Could not refresh analytics.")); }, [currentOrg, currentSite, queryKey]);
  useEffect(refresh, [refresh]);
  function updateCard(index: number, card: DashboardCard) { setCards((current) => current.map((item, i) => i === index ? { ...card, id: item.id } : item)); setDirty(true); setEditingIndex(null); }
  function move(index: number, delta: number) { const target = index + delta; if (target < 0 || target >= cards.length) return; const next = [...cards]; [next[index], next[target]] = [next[target], next[index]]; setCards(next); setDirty(true); }
  function moveCard(from: number, to: number) { if (from === to || from < 0 || to < 0) return; setCards((current) => { const next = [...current]; const [moved] = next.splice(from, 1); next.splice(to, 0, moved); return next; }); setDirty(true); }
  async function save() { if (!currentOrg || !currentSite || !name.trim() || !canMutate) return; setSaving(true); setPageError(undefined); try { const payload = { name: name.trim(), description: description.trim() || null, cards: cards.map((c) => ({ ...c, position: undefined })) }; const saved = mode === "new" ? await dashboardsApi.createDashboard(currentOrg.orgId, currentSite.id, payload) : await dashboardsApi.updateDashboard(currentOrg.orgId, currentSite.id, dashboardId!, payload); setDirty(false); navigate(`/dashboard/${saved.id}`, { replace: true }); } catch (e) { setPageError(e instanceof Error ? e.message : "Save failed."); } finally { setSaving(false); } }
  function back() { if (!dirty || window.confirm("Discard unsaved dashboard changes?")) navigate(mode === "new" ? "/dashboard" : `/dashboard/${dashboardId}`); }
  if (!currentSite && !workspaceLoading) return <EmptyState icon={<LayoutDashboard />} title="Select a site" description="Choose a site before opening a dashboard." />;
  if (loading) return <LoadingRows />;
  const headerTitle = editingName ? <Input ref={nameInputRef} aria-label="Dashboard name" className="h-9 w-full max-w-xl text-2xl font-medium" placeholder="Dashboard name" value={name} onChange={(e) => { setName(e.target.value); setDirty(true); }} onBlur={() => setEditingName(false)} onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); e.currentTarget.blur(); } }} /> : <span className="inline-flex items-center gap-2">{name || (mode === "new" ? "New dashboard" : "Dashboard")}{editable && <Button type="button" variant="ghost" size="icon" className="h-7 w-7" aria-label="Edit dashboard name" onClick={() => setEditingName(true)}><Pencil className="h-4 w-4" /></Button>}</span>;
  const headerDescription = editingDescription ? <Textarea ref={descriptionInputRef} aria-label="Dashboard description" className="mt-1 min-h-9 max-w-2xl resize-none py-1 text-[13px] leading-relaxed" placeholder="Description (optional)" rows={1} value={description} onChange={(e) => { setDescription(e.target.value); setDirty(true); }} onBlur={() => setEditingDescription(false)} onKeyDown={(e) => { if (e.key === "Escape") e.currentTarget.blur(); }} /> : <span className="inline-flex items-center gap-1.5">{description || (mode === "view" ? "No description." : "Edit Description")}{editable && <Button type="button" variant="ghost" size="icon" className="h-6 w-6" aria-label="Edit dashboard description" onClick={() => setEditingDescription(true)}><Pencil className="h-3.5 w-3.5" /></Button>}</span>;
  return <div><PageHeader section="Workspace" title={headerTitle} description={headerDescription} actions={<div className="flex gap-2"><Button variant="outline" onClick={back}><ArrowLeft />Back</Button>{mode === "view" && canMutate && <Button onClick={() => navigate(`/dashboard/${dashboardId}/edit`)}>Edit dashboard</Button>}{editable && <Button disabled={saving || !name.trim()} onClick={() => void save()}><Save />{saving ? "Saving…" : "Save dashboard"}</Button>}</div>} />
    {pageError && <div className="mb-4"><ErrorNotice>{pageError}</ErrorNotice></div>}
    <DashboardFilterBar value={filters} segments={segments} onChange={setFilters} />
    {editable && <Button className="mb-4" variant="outline" disabled={!catalog} onClick={() => setEditingIndex("new")}><Plus />Add card</Button>}
    {!cards.length ? <EmptyState icon={<LayoutDashboard />} title="No cards yet" description={editable ? "Add a Metrics, Funnel, or Retention card." : "This dashboard has no cards."} action={editable ? <Button className="mt-3" onClick={() => setEditingIndex("new")}><Plus />Add card</Button> : undefined} /> : <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">{cards.map((card, index) => { const key = cardKey(card, index); return <DashboardCardView key={key} card={card} response={results[key]} loading={!results[key] && !errors[key]} error={errors[key]} filters={filters} editable={editable} draggable={editable} onDragStart={() => setDraggingIndex(index)} onDragOver={() => {}} onDrop={() => { if (draggingIndex !== null) moveCard(draggingIndex, index); setDraggingIndex(null); }} onRetry={refresh} onEdit={() => setEditingIndex(index)} onDuplicate={() => { setCards((c) => [...c.slice(0, index + 1), { ...card, id: undefined, title: `${card.title} copy` }, ...c.slice(index + 1)]); setDirty(true); }} onDelete={() => { setCards((c) => c.filter((_, i) => i !== index)); setDirty(true); }} onMove={(delta) => move(index, delta)} onDrilldown={() => { if (!currentOrg || !currentSite) return; analyticsApi.drilldown(currentOrg.orgId, currentSite.id, filters, card.configuration, { offset: 0, limit: 50, ...(card.configuration.kind === "funnel" ? { stepIndex: 0 } : {}) }).then((response) => setDetails({ kind: response.kind, items: (response.items ?? response.users ?? []) as Record<string, unknown>[], total: response.total })).catch((e) => setPageError(e instanceof Error ? e.message : "Could not load details.")); }} />; })}</div>}
    {catalog && currentOrg && currentSite && editingIndex !== null && <CardEditorDialog open card={typeof editingIndex === "number" ? cards[editingIndex] : undefined} orgId={currentOrg.orgId} siteId={currentSite.id} filters={filters} catalog={catalog} events={events} funnels={funnels} segments={segments} onClose={() => setEditingIndex(null)} onSave={(card) => { if (editingIndex === "new") setCards((c) => [...c, card]); else updateCard(editingIndex, card); setDirty(true); setEditingIndex(null); }} />}
    <Dialog open={Boolean(details)} onOpenChange={(open) => !open && setDetails(undefined)}><DialogContent><DialogHeader><DialogTitle>Underlying {details?.kind}</DialogTitle></DialogHeader><div className="max-h-[60vh] overflow-y-auto"><p className="mb-3 text-sm text-muted-foreground">Showing {details?.items.length ?? 0} of {details?.total ?? 0}</p>{details?.items.map((item, index) => <button key={String(item.id ?? item.sessionId ?? item.trackedUserId ?? item.anonymousId ?? index)} className="block w-full border-t px-2 py-3 text-left text-sm hover:bg-muted" onClick={() => { const path = detailPath(details.kind, item); if (path) navigate(path); }}>{String(item.externalUserId ?? item.anonymousId ?? item.eventName ?? item.sessionId ?? item.id ?? "Detail")}</button>)}</div></DialogContent></Dialog>
  </div>;
}
function cardKey(card: DashboardCard, index: number) { return card.id ?? `draft-${index}`; }
function semanticQuery(card: DashboardCard) { const c = structuredClone(card.configuration) as any; delete c.visualization; delete c.target; return c; }
function detailPath(kind: string, item: Record<string, unknown>) { if (kind === "sessions" && item.sessionId) return `/observe/sessions/${item.sessionId}`; if (item.trackedUserId) return `/users/${item.trackedUserId}`; if (item.anonymousId && kind === "users") return `/users/anonymous/${item.anonymousId}`; if (kind === "occurrences" && item.eventName) return `/observe/events/${encodeURIComponent(String(item.eventName))}?tab=occurrences&occurrence=${item.id}`; return null; }
