import { useEffect, useState } from "react";
import * as experiencesApi from "@/api/experiences";
import type { ExperienceAnalytics, SurveyResponseRecord } from "@/types/experiences";
import { Button } from "@/components/ui/button";

export function ExperienceAnalyticsView({ orgId, siteId, experienceId }: { orgId: string; siteId: string; experienceId: string }) {
  const [analytics, setAnalytics] = useState<ExperienceAnalytics>();
  const [responses, setResponses] = useState<SurveyResponseRecord[]>([]);
  const [tab, setTab] = useState<"overview" | "responses">("overview");
  const [error, setError] = useState<string>();
  useEffect(() => { setError(undefined); experiencesApi.getExperienceAnalytics(orgId, siteId, experienceId).then(setAnalytics).catch(error => setError(error instanceof Error ? error.message : "Analytics could not be loaded.")); }, [orgId, siteId, experienceId]);
  useEffect(() => { if (tab !== "responses") return; experiencesApi.listSurveyResponses(orgId, siteId, experienceId).then(result => setResponses(result.responses)).catch(error => setError(error instanceof Error ? error.message : "Responses could not be loaded.")); }, [tab, orgId, siteId, experienceId]);
  if (error) return <p className="text-sm text-destructive">{error}</p>;
  if (!analytics) return <p className="text-sm text-muted-foreground">Loading analytics...</p>;
  const cards = analytics.survey ? [["Seen", analytics.survey.usersSeen], ["Started", analytics.survey.started], ["Submitted", analytics.survey.submitted], ["Response rate", `${analytics.survey.responseRate}%`], ["Abandoned", analytics.survey.abandoned]] : [["Users seen", analytics.summary.usersSeen], ["Started", analytics.summary.usersStarted], ["Completed", analytics.summary.completed], ["Completion rate", `${analytics.summary.completionRate}%`], ["Dismissed", analytics.summary.dismissed]];
  return <div className="space-y-5">
    {analytics.survey && <div className="flex gap-2"><Button size="sm" variant={tab === "overview" ? "default" : "outline"} onClick={() => setTab("overview")}>Overview</Button><Button size="sm" variant={tab === "responses" ? "default" : "outline"} onClick={() => setTab("responses")}>Responses</Button></div>}
    {tab === "overview" ? <>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{cards.map(([label, value]) => <div key={label} className="rounded-lg border bg-background p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>)}</div>
      {analytics.trend.length > 0 && <section><h3 className="mb-3 font-semibold">Trend over time</h3><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th className="p-2 text-left">Date</th><th className="p-2 text-right">Seen</th><th className="p-2 text-right">{analytics.survey ? "Submitted" : "Completed"}</th><th className="p-2 text-right">Dismissed</th></tr></thead><tbody>{analytics.trend.map(point => <tr key={point.date} className="border-t"><td className="p-2">{point.date}</td><td className="p-2 text-right">{point.usersSeen}</td><td className="p-2 text-right">{analytics.survey ? point.submitted : point.completed}</td><td className="p-2 text-right">{point.dismissed}</td></tr>)}</tbody></table></div></section>}
      {analytics.guide && <section><h3 className="mb-3 font-semibold">Step funnel</h3><div className="space-y-2">{analytics.guide.steps.map(step => <div key={step.stepId} className="grid grid-cols-[80px_1fr_auto] items-center gap-3 rounded border p-3 text-sm"><span>Step {step.stepIndex + 1}</span><div className="h-2 rounded bg-muted"><div className="h-2 rounded bg-blue-600" style={{ width: `${analytics.summary.usersSeen ? step.usersReached / analytics.summary.usersSeen * 100 : 0}%` }} /></div><span>{step.usersReached} reached · {step.dropOff} dropped · {Math.round(step.averageDurationMs / 100) / 10}s avg</span></div>)}</div></section>}
      {analytics.survey && <section className="space-y-4"><h3 className="font-semibold">Question results</h3>{analytics.survey.questions.map(question => <div key={question.questionId} className="rounded-lg border p-4"><p className="font-medium">{question.label}</p><p className="text-xs text-muted-foreground">{question.responseCount} responses</p>{question.distribution?.map(item => <div key={item.value} className="mt-2 flex justify-between text-sm"><span>{item.value}</span><span>{item.count} ({item.percent}%)</span></div>)}{question.textResponses?.slice(0, 20).map((text, index) => <p key={index} className="mt-2 rounded bg-muted p-2 text-sm">{text}</p>)}</div>)}</section>}
    </> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th className="p-2 text-left">Response</th><th className="p-2 text-left">User</th><th className="p-2 text-left">Status</th><th className="p-2 text-left">Answers</th></tr></thead><tbody>{responses.map(response => <tr key={response.responseId} className="border-t"><td className="p-2">{new Date(response.startedAt).toLocaleString()}</td><td className="p-2">{response.trackedUserId ?? response.anonymousId}</td><td className="p-2">{response.submittedAt ? "Submitted" : response.abandonedAt ? "Abandoned" : "Started"}</td><td className="p-2"><pre className="max-w-md whitespace-pre-wrap text-xs">{JSON.stringify(response.answers, null, 2)}</pre></td></tr>)}</tbody></table></div>}
  </div>;
}
