import type { Component, Editor } from "grapesjs";
import { describe, expect, it, vi } from "vitest";
import { validateBuilderCss } from "./widgetBuilder";
import { clientPointToWidgetSpace, FREE_AREA_CLASS, FREE_AREA_CLASS_PREFIX, FREE_LAYOUT_ITEM_CLASS, FREE_LAYOUT_ITEM_CLASS_PREFIX, getElementBoxInWidgetSpace, installWidgetInteractions, isFreeArea, resizeOptionsForComponent, rootResizeResult } from "./grapesWidgetInteractions";

interface Rect { left: number; top: number; width: number; height: number }
interface Fixture { component: Component; element: HTMLElement; children: Fixture[]; values: Map<string, unknown>; classes: () => string[]; dragMode: () => string; setRect: (rect: Partial<Rect>) => void; setParent: (parent?: Fixture) => void }

function fixture({ classes = [], tagName = "div", rect = { left: 0, top: 0, width: 100, height: 40 }, parent }: { classes?: string[]; tagName?: string; rect?: Rect; parent?: Fixture } = {}): Fixture {
  let currentParent = parent; let currentRect = { ...rect }; let currentStyle: Record<string, string> = {}; let dragMode = ""; const currentClasses = [...classes]; const values = new Map<string, unknown>(); const children: Fixture[] = []; const element = document.createElement(tagName); const result = {} as Fixture;
  Object.defineProperties(element, { offsetWidth: { configurable: true, get: () => currentRect.width }, offsetHeight: { configurable: true, get: () => currentRect.height }, clientWidth: { configurable: true, get: () => currentRect.width }, clientHeight: { configurable: true, get: () => currentRect.height } }); element.getBoundingClientRect = () => ({ ...currentRect, x: currentRect.left, y: currentRect.top, right: currentRect.left + currentRect.width, bottom: currentRect.top + currentRect.height, toJSON: () => ({}) });
  const component = { getClasses: () => [...currentClasses], addClass: (value: string | string[]) => { for (const name of Array.isArray(value) ? value : value.split(/\s+/)) if (name && !currentClasses.includes(name)) currentClasses.push(name); }, removeClass: (value: string | string[]) => { for (const name of Array.isArray(value) ? value : value.split(/\s+/)) { const index = currentClasses.indexOf(name); if (index >= 0) currentClasses.splice(index, 1); } }, get: (key: string) => key === "tagName" ? tagName : values.get(key), set: (key: string, value: unknown) => values.set(key, value), getEl: () => element, getStyle: () => ({ ...currentStyle }), setStyle: (value: Record<string, string>) => { currentStyle = { ...value }; }, setDragMode: (value = "") => { dragMode = value; }, parent: () => currentParent?.component, components: () => ({ forEach: (callback: (child: Component) => void) => children.forEach(child => callback(child.component)) }), is: (type: string) => type === "image" && tagName === "img", index: () => currentParent?.children.indexOf(result) ?? 0, move: (_parent: Component, options: { at?: number }) => { if (currentParent && options.at !== undefined) { currentParent.children.splice(currentParent.children.indexOf(result), 1); currentParent.children.splice(options.at, 0, result); } }, remove: vi.fn(), getAttributes: () => ({}) } as unknown as Component;
  Object.assign(result, { component, element, children, values, classes: () => [...currentClasses], dragMode: () => dragMode, setRect: (value: Partial<Rect>) => { currentRect = { ...currentRect, ...value }; }, setParent: (next?: Fixture) => { if (currentParent) currentParent.children.splice(currentParent.children.indexOf(result), 1); currentParent = next; if (next) { next.children.push(result); next.element.appendChild(element); } } }); if (parent) { parent.children.push(result); parent.element.appendChild(element); } return result;
}

function harness(root: Fixture) {
  const handlers = new Map<string, (...args: any[]) => void>(); const rules = new Map<string, any>(); const canvasDocument = document.implementation.createHTMLDocument(); canvasDocument.body.appendChild(root.element); let selected: Component | undefined; let editing: Component | undefined;
  const Css = { setRule: vi.fn((selector: string, style: Record<string, string>) => { const rule = { selector, style: { ...style }, getStyle: () => ({ ...rule.style }), selectorsToString: () => selector }; rules.set(selector, rule); return rule; }), getRule: vi.fn((selector: string) => rules.get(selector)), getRules: vi.fn(() => [...rules.values()]), remove: vi.fn((target: string | { selector: string }) => rules.delete(typeof target === "string" ? target : target.selector)) };
  const editor = { Css, Canvas: { getDocument: () => canvasDocument }, UndoManager: { isTracking: () => true, stop: vi.fn(), start: vi.fn() }, getSelected: () => selected, getEditing: () => editing, getWrapper: () => ({ find: (selector: string) => selector === ".movecues-widget" ? [root.component] : [] }), on: (name: string, handler: (...args: any[]) => void) => handlers.set(name, handler) } as unknown as Editor;
  return { editor, handlers, rules, select: (value?: Component) => { selected = value; }, edit: (value?: Component) => { editing = value; }, css: () => [...rules.values()].map(rule => `${rule.selector}{${Object.entries(rule.style).map(([key, value]) => `${key}:${value}`).join(";")}}`).join("") };
}

function pointer(type: string, pointerId: number, clientX: number, clientY: number): Event { const event = new Event(type, { bubbles: true, cancelable: true }); Object.defineProperties(event, { pointerId: { value: pointerId }, clientX: { value: clientX }, clientY: { value: clientY }, button: { value: 0 }, isPrimary: { value: true } }); return event; }
const design = { width: "md" as const, theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" as const } };

describe("Free Area interactions", () => {
  it("keeps the area in flow and frees only direct children", () => {
    const root = fixture({ classes: ["movecues-widget"], rect: { left: 0, top: 0, width: 600, height: 500 } }); const area = fixture({ classes: [FREE_AREA_CLASS], rect: { left: 20, top: 100, width: 560, height: 240 }, parent: root }); const container = fixture({ classes: ["movecues-widget__container"], rect: { left: 40, top: 120, width: 300, height: 100 }, parent: area }); const nested = fixture({ classes: ["movecues-widget__body"], tagName: "p", parent: container }); const test = harness(root); installWidgetInteractions(test.editor, { widgetType: "modal", design: () => design, onRootResize: vi.fn() }); test.handlers.get("component:add")?.(area.component);
    expect(isFreeArea(area.component)).toBe(true); expect(area.dragMode()).toBe(""); expect(area.classes().some(name => name.startsWith(FREE_AREA_CLASS_PREFIX))).toBe(true); expect(container.classes()).toContain(FREE_LAYOUT_ITEM_CLASS); expect(container.dragMode()).toBe("absolute"); expect(nested.classes()).not.toContain(FREE_LAYOUT_ITEM_CLASS); expect(test.css()).toContain("min-height:240px"); expect(validateBuilderCss(test.css())).toBe(test.css()); expect(resizeOptionsForComponent(root.component, "modal")).toMatchObject({ tl: true, br: true });
  });

  it.each([0.6, 1, 1.5])("stores logical geometry and drag offset at %sx", scale => {
    const root = fixture({ classes: ["movecues-widget"], rect: { left: 0, top: 0, width: 800, height: 700 } }); const area = fixture({ classes: [FREE_AREA_CLASS], rect: { left: 100, top: 80, width: 600, height: 500 }, parent: root }); const item = fixture({ classes: ["movecues-widget__button"], tagName: "button", rect: { left: 100 + 100 * scale, top: 80 + 80 * scale, width: 200 * scale, height: 60 * scale }, parent: area }); area.element.getBoundingClientRect = () => ({ left: 100, top: 80, width: 600 * scale, height: 500 * scale, right: 100 + 600 * scale, bottom: 80 + 500 * scale, x: 100, y: 80, toJSON: () => ({}) }); const test = harness(root); const onMutation = vi.fn(); const controller = installWidgetInteractions(test.editor, { widgetType: "modal", design: () => design, onRootResize: vi.fn(), onMutation }); test.handlers.get("component:add")?.(area.component); test.select(item.component); controller.select(item.component); onMutation.mockClear(); expect(controller.getFreeItemBox(item.component)).toMatchObject({ x: 100, y: 80, width: 200, height: 60 }); item.element.dispatchEvent(pointer("pointerdown", 1, 100 + 150 * scale, 80 + 100 * scale)); item.element.dispatchEvent(pointer("pointermove", 1, 100 + 400 * scale, 80 + 300 * scale)); item.element.dispatchEvent(pointer("pointerup", 1, 100 + 400 * scale, 80 + 300 * scale)); expect(controller.getFreeItemBox(item.component)).toMatchObject({ x: 350, y: 280 }); expect(onMutation).toHaveBeenCalledTimes(1);
  });

  it("cleans items moved out and recalculates items moved between areas", () => {
    const root = fixture({ classes: ["movecues-widget"], rect: { left: 0, top: 0, width: 800, height: 700 } }); const first = fixture({ classes: [FREE_AREA_CLASS], rect: { left: 0, top: 0, width: 400, height: 300 }, parent: root }); const second = fixture({ classes: [FREE_AREA_CLASS], rect: { left: 400, top: 0, width: 400, height: 300 }, parent: root }); const item = fixture({ classes: ["movecues-widget__body"], tagName: "p", rect: { left: 50, top: 40, width: 200, height: 50 }, parent: first }); const test = harness(root); const controller = installWidgetInteractions(test.editor, { widgetType: "modal", design: () => design, onRootResize: vi.fn() }); controller.syncFreeAreas(); item.setParent(second); item.setRect({ left: 470, top: 60 }); test.handlers.get("component:add")?.(item.component); expect(controller.getFreeItemBox(item.component)).toMatchObject({ x: 70, y: 60 }); item.setParent(root); test.handlers.get("component:add")?.(item.component); expect(item.classes()).not.toContain(FREE_LAYOUT_ITEM_CLASS); expect(item.classes().some(name => name.startsWith(FREE_LAYOUT_ITEM_CLASS_PREFIX))).toBe(false); expect(test.rules.size).toBe(2);
  });

  it("rejects nested areas", () => { const root = fixture({ classes: ["movecues-widget"] }); const area = fixture({ classes: [FREE_AREA_CLASS], parent: root }); const nested = fixture({ classes: [FREE_AREA_CLASS], parent: area }); const test = harness(root); installWidgetInteractions(test.editor, { widgetType: "modal", design: () => design, onRootResize: vi.fn() }); test.handlers.get("component:add")?.(nested.component); expect(nested.component.remove).toHaveBeenCalled(); });

  it("suspends movement during RTE editing and persists once it ends", () => {
    const root = fixture({ classes: ["movecues-widget"] }); const area = fixture({ classes: [FREE_AREA_CLASS], rect: { left: 0, top: 0, width: 500, height: 300 }, parent: root }); const text = fixture({ classes: ["movecues-widget__body"], tagName: "p", rect: { left: 40, top: 30, width: 200, height: 50 }, parent: area }); const test = harness(root); const onMutation = vi.fn(); const controller = installWidgetInteractions(test.editor, { widgetType: "modal", design: () => design, onRootResize: vi.fn(), onMutation }); controller.syncFreeAreas(); test.select(text.component); controller.select(text.component); test.edit(text.component); test.handlers.get("rte:enable")?.(); onMutation.mockClear(); text.element.setAttribute("contenteditable", "true"); text.element.dispatchEvent(pointer("pointerdown", 2, 60, 40)); text.element.dispatchEvent(pointer("pointermove", 2, 300, 200)); text.element.dispatchEvent(pointer("pointerup", 2, 300, 200)); expect(controller.getFreeItemBox(text.component)).toMatchObject({ x: 40, y: 30 }); expect(controller.isEditing()).toBe(true); test.edit(); test.handlers.get("rte:disable")?.(); expect(controller.isEditing()).toBe(false); expect(onMutation).toHaveBeenCalledTimes(1);
  });

  it("normalizes geometry relative to the supplied area", () => { const area = document.createElement("div"); const item = document.createElement("div"); Object.defineProperties(area, { offsetWidth: { value: 600 }, offsetHeight: { value: 500 } }); area.getBoundingClientRect = () => ({ left: 300, top: 200, width: 360, height: 300, right: 660, bottom: 500, x: 300, y: 200, toJSON: () => ({}) }); item.getBoundingClientRect = () => ({ left: 420, top: 260, width: 180, height: 30, right: 600, bottom: 290, x: 420, y: 260, toJSON: () => ({}) }); expect(getElementBoxInWidgetSpace(item, area)).toEqual({ x: 200, y: 100, width: 300, height: 50 }); expect(clientPointToWidgetSpace(540, 380, area)).toEqual({ x: 400, y: 300 }); expect(rootResizeResult("modal", design, { w: 360, h: 300 }, { width: "600px", height: "500px" })?.size).toEqual({ width: { mode: "fixed", value: 600 }, height: { mode: "fixed", value: 500 } }); });

  it("persists anchored-card vertical root resizing as a constrained fixed height", () => {
    const root = fixture({ classes: ["movecues-widget"] });
    expect(resizeOptionsForComponent(root.component, "anchored_card")).toMatchObject({ tl: true, bc: true, br: true });
    expect(rootResizeResult("anchored_card", design, { w: 360, h: 260 }, { width: "360px", height: "260px" })?.size).toEqual({ width: { mode: "fixed", value: 360 }, height: { mode: "fixed", value: 260 } });
    expect(rootResizeResult("anchored_card", design, { w: 320, h: 1 }, { height: "1px" })?.size.height).toEqual({ mode: "fixed", value: 120 });
    expect(rootResizeResult("anchored_card", design, { w: 320, h: 900 }, { height: "900px" })?.size.height).toEqual({ mode: "fixed", value: 700 });
  });
});
