import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { beforeEach, describe, expect, it, vi } from "vitest";
import * as workspace from "../../auth/WorkspaceContext";
import * as experiencesApi from "../../api/experiences";
import * as segmentsApi from "../../api/segments";
import type { Experience, ExperienceAnalytics } from "../../types/experiences";
import { SurveyResultsPage } from "./SurveyResultsPage";

vi.mock("../../auth/WorkspaceContext"); vi.mock("../../api/experiences"); vi.mock("../../api/segments");
const mockedWorkspace = vi.mocked(workspace); const mockedExperiences = vi.mocked(experiencesApi); const mockedSegments = vi.mocked(segmentsApi);
const question = { id: "q_rating", type: "rating" as const, label: "How easy was setup?", min: 1, max: 5 };
const experience: Experience = { id: "exp_survey", siteId: "site_1", kind: "widget", widgetType: "survey", name: "Onboarding feedback", status: "published", buildPageId: null, buildUrl: "https://app.example.com", publishedVersionId: "v1", createdBy: "u1", createdAt: "2026-01-01", updatedAt: "2026-01-02", draftVersion: null, publishedVersion: null };
const analytics: ExperienceAnalytics = { experience: { id: experience.id, name: experience.name, kind: "widget", widgetType: "survey" }, summary: { usersSeen: 10, usersStarted: 4, completed: 0, dismissed: 0, completionRate: 0 }, guide: null, checklist: null, survey: { usersSeen: 10, started: 4, submitted: 3, responseCount: 4, abandoned: 1, responseRate: 30, abandonmentRate: 25, averageCompletionTimeMs: 43000, medianCompletionTimeMs: 42000, questions: [{ schemaKey: "rating-schema", questionId: question.id, label: question.label, type: question.type, question, versionIds: ["v1"], historical: false, responseCount: 4, distribution: [{ value: "4", label: "4", count: 3, percent: 75 }], average: 4, median: 4, mode: 4, min: 1, max: 5 }], commonResponses: [{ schemaKey: "rating-schema", questionId: question.id, label: question.label, value: "4", displayValue: "4", count: 3, percent: 75, historical: false }], investigationGroups: [{ schemaKey: "rating-schema", questionId: question.id, label: question.label, value: "4", displayValue: "4", count: 3, percent: 75, historical: false, observation: "3 respondents selected “4”." }], latestFeedback: [{ responseId: "r1", questionId: "q_text", questionLabel: "What could improve?", text: "Invites were confusing", submittedAt: "2026-01-02T10:00:00.000Z", respondent: { identityKey: "anon_1", identityType: "anonymous", trackedUserId: null, externalUserId: null, anonymousId: "anon_1", displayName: "Anonymous visitor", email: null, profilePath: "/users/anonymous/anon_1", lastSeenAt: null } }] }, trend: [{ date: "2026-01-02", usersSeen: 10, interacted: 4, completed: 0, dismissed: 0, submitted: 3, starts: 4, responses: 4, abandoned: 1, responseRate: 30, abandonmentRate: 25 }] };

function ready() { mockedWorkspace.useWorkspace.mockReturnValue({ orgs: [], currentOrg: { orgId: "org_1", name: "Acme", role: "OWNER" }, setCurrentOrgId: vi.fn(), sites: [], currentSite: { id: "site_1", siteId: "public_1", name: "App", domain: "app.example.com" }, setCurrentSiteId: vi.fn(), loading: false, error: null, refreshSites: vi.fn() }); mockedExperiences.getExperience.mockResolvedValue(experience); mockedExperiences.getExperienceAnalytics.mockResolvedValue(analytics); mockedExperiences.listSurveyResponses.mockResolvedValue({ total: 0, limit: 5, offset: 0, responses: [] }); }
function view(tab: "overview" | "responses" | "investigate", path: string) { return render(<MemoryRouter initialEntries={[path]}><Routes><Route path="/experiences/:experienceId/results/*" element={<SurveyResultsPage tab={tab} />} /><Route path="/segments/:segmentId" element={<div>Segment created</div>} /></Routes></MemoryRouter>); }

describe("SurveyResultsPage", () => {
  beforeEach(() => { vi.clearAllMocks(); ready(); });
  it("renders the full survey overview without mounting the builder", async () => { view("overview", "/experiences/exp_survey/results"); expect(await screen.findByRole("heading", { name: "Onboarding feedback" })).toBeInTheDocument(); expect(screen.getByText("How did people respond?")).toBeInTheDocument(); expect(screen.getByText(/Invites were confusing/)).toBeInTheDocument(); expect(screen.getByText("Most common responses")).toBeInTheDocument(); expect(screen.queryByLabelText("Builder experience key")).not.toBeInTheDocument(); expect(mockedExperiences.listSurveyResponses).not.toHaveBeenCalled(); });
  it("lazy-loads and paginates display-ready responses", async () => { mockedExperiences.listSurveyResponses.mockResolvedValue({ total: 1, limit: 25, offset: 0, responses: [{ responseId: "r1", experienceId: experience.id, versionId: "v1", impressionId: "i1", anonymousId: "anon_1", trackedUserId: null, sessionId: "s1", answers: { [question.id]: 4 }, answerDetails: [{ questionId: question.id, label: question.label, type: "rating", value: 4, displayValue: "4", malformed: false }], respondent: analytics.survey!.latestFeedback![0].respondent, startedAt: "2026-01-02T09:59:18.000Z", submittedAt: "2026-01-02T10:00:00.000Z", abandonedAt: null }] }); view("responses", "/experiences/exp_survey/results/responses"); expect(await screen.findByText("Who responded?")).toBeInTheDocument(); expect(await screen.findByText("Anonymous visitor")).toBeInTheDocument(); expect(mockedExperiences.listSurveyResponses).toHaveBeenCalledTimes(1); fireEvent.click(screen.getByRole("button", { name: "View response from Anonymous visitor" })); expect(await screen.findByText("Response details")).toBeInTheDocument(); expect(screen.getAllByText(question.label)).toHaveLength(2); });
  it("creates a date-scoped dynamic segment from an investigated answer", async () => { mockedSegments.createSegment.mockResolvedValue({ id: "seg_1", siteId: "site_1", name: "Onboarding feedback — 4", description: null, definition: { logic: "and", conditions: [] }, audienceCount: 3, createdAt: "2026-01-01", updatedAt: "2026-01-01" }); view("investigate", "/experiences/exp_survey/results/investigate?range=30&questionId=q_rating&answer=4"); expect(await screen.findByText("Investigate this group")).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Create segment" })); fireEvent.click(await screen.findByRole("button", { name: "Create segment" })); await waitFor(() => expect(mockedSegments.createSegment).toHaveBeenCalledWith("org_1", "site_1", expect.objectContaining({ definition: { logic: "and", conditions: [expect.objectContaining({ type: "survey_response", experienceId: experience.id, dateRange: { type: "relative", days: 30 } })] } }))); expect(await screen.findByText("Segment created")).toBeInTheDocument(); });
});
