import { useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { useWorkspace } from "../../auth/WorkspaceContext";
import { PageHeader } from "../../components/PageHeader";
import { EmptyState } from "../../components/EmptyState";
import * as eventsApi from "../../api/events";
import * as segmentsApi from "../../api/segments";
import type { EventDefinitionSummary } from "../../types/api";
import { formatTimestamp } from "../../lib/format";
import { Button } from "@/components/ui/button";
import { AnalyticsFilterBar, type AppliedFilters, type FilterDefinition } from "@/components/filters/AnalyticsFilterBar";
import { readFilters, writeFilters } from "@/components/filters/filterUrlState";
import { resolveDateRange, type DateRangePreset } from "@/lib/dateRange";
import { DataTableFrame, ErrorNotice, LoadingRows, dataTableClass } from "@/components/PageSurface";

export function EventsPage() {
  const { currentOrg, currentSite } = useWorkspace(); const navigate = useNavigate(); const [params, setParams] = useSearchParams();
  const [events, setEvents] = useState<EventDefinitionSummary[] | null>(null); const [total, setTotal] = useState(0); const [error, setError] = useState<string | null>(null); const [segments, setSegments] = useState<{ id: string; name: string }[]>([]);
  const filterQuery = params.toString(); const filters = readFilters(params, ["range", "segmentId"]); const range = resolveDateRange((filters.range?.[0] ?? "30d") as DateRangePreset); const search = params.get("search") ?? ""; const sort = params.get("sort") ?? "occurrences";
  const definitions: FilterDefinition[] = [{ key: "range", label: "Date range", options: [{ value: "today", label: "Today" }, { value: "7d", label: "Last 7 days" }, { value: "30d", label: "Last 30 days" }, { value: "90d", label: "Last 90 days" }] }, { key: "segmentId", label: "Segment", options: segments.map((item) => ({ value: item.id, label: item.name })) }];
  const update = (next: URLSearchParams) => setParams(next, { replace: true }); const setFilters = (next: AppliedFilters) => update(writeFilters(params, next, definitions.map((item) => item.key)));
  useEffect(() => { if (!currentOrg || !currentSite || !range) return; let active = true; setEvents(null); setError(null); eventsApi.listEvents(currentOrg.orgId, currentSite.id, { search: search || undefined, since: range.since, until: range.until, segmentId: filters.segmentId?.[0], sort, limit: 100 }).then((response) => { if (active) { setEvents(response.events); setTotal(response.total); } }).catch(() => { if (active) setError("Couldn't load events."); }); return () => { active = false; }; }, [currentOrg, currentSite, filterQuery]);
  if (!currentSite) return <><PageHeader section="Observe" title="Events" description="Track and explore the application events your product sends." /><DataTableFrame><EmptyState title="No site selected" description="Select a site from the switcher above." /></DataTableFrame></>;
  const hasFilters = Boolean(search || filters.segmentId);
  return <><PageHeader section="Observe" title="Events" description="Application events reported with analytics.event(name, properties)." /><AnalyticsFilterBar definitions={definitions} values={filters} onChange={setFilters} onOpen={() => { if (currentOrg && currentSite && segments.length === 0) void segmentsApi.listSegments(currentOrg.orgId, currentSite.id, { limit: 100 }).then((response) => setSegments(response.segments)).catch(() => setSegments([])); }} search={search} onSearchChange={(value) => { const next = new URLSearchParams(params); value ? next.set("search", value) : next.delete("search"); update(next); }} searchPlaceholder="Search events…" sort={sort} onSortChange={(value) => { const next = new URLSearchParams(params); next.set("sort", value); update(next); }} sortOptions={[{ value: "occurrences", label: "Occurrences" }, { value: "users", label: "Unique users" }, { value: "sessions", label: "Sessions" }, { value: "lastSeen", label: "Last triggered" }, { value: "firstSeen", label: "First seen" }, { value: "az", label: "A–Z" }, { value: "za", label: "Z–A" }]} /><DataTableFrame>{error && <div className="p-4"><ErrorNotice>{error}</ErrorNotice></div>}{!error && events === null && <LoadingRows />}{!error && events && events.length === 0 && <EmptyState title={hasFilters ? "No results match these filters" : "No events recorded yet"} description={hasFilters ? "Try changing or clearing filters." : "Track your first application event with analytics.event(name, properties)."} action={hasFilters ? <Button variant="outline" onClick={() => setFilters({})}>Clear filters</Button> : undefined} />}{events && events.length > 0 && <table className={dataTableClass}><thead><tr><th>Event</th><th>Occurrences</th><th>Unique users</th><th>Sessions</th><th>First seen</th><th>Last seen</th></tr></thead><tbody>{events.map((event) => <tr key={event.name} onClick={() => navigate(`/observe/events/${encodeURIComponent(event.name)}`)}><td className="mono max-w-sm break-all font-medium text-foreground">{event.name}</td><td className="mono">{event.occurrences.toLocaleString()}</td><td className="mono">{event.uniqueUsers.toLocaleString()} users</td><td className="mono">{event.sessions.toLocaleString()} sessions</td><td className="text-muted-foreground">{formatTimestamp(event.firstSeenAt)}</td><td className="text-muted-foreground">{formatTimestamp(event.lastSeenAt)}</td></tr>)}</tbody></table>}</DataTableFrame>{events && <p className="mt-2 text-xs text-muted-foreground">{total} events</p>}</>;
}
