import { useEffect, useMemo, useState } from "react";
import { Search } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@movecues/ui";
import { Button } from "@movecues/ui";
import { Input } from "@movecues/ui";
import { Label } from "@movecues/ui";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@movecues/ui";
import { Checkbox } from "@movecues/ui";
import * as analyticsApi from "@/api/analytics";
import * as experiencesApi from "@/api/experiences";
import type { AnalyticsCatalog, AnalyticsResponse, DashboardCard, DashboardCardConfiguration, DashboardFilters, EventDefinitionSummary, ExperienceCardConfiguration, FunnelListItem, MetricCardConfiguration, Segment } from "@/types/api";
import type { Experience } from "@/types/experiences";
import { DashboardCardView } from "./DashboardCardView";

const defaultMetric = (): MetricCardConfiguration => ({ schemaVersion: 1, kind: "metric", metricId: "users.unique", mode: "trend", visualization: "line" });
function defaultConfig(kind: DashboardCardConfiguration["kind"]): DashboardCardConfiguration { return kind === "metric" ? defaultMetric() : kind === "funnel" ? { schemaVersion: 1, kind, funnelId: "" } : kind === "experience" ? { schemaVersion: 1, kind, experienceType: "guide", experienceId: "", metric: "users_seen", visualization: "total" } : { schemaVersion: 1, kind, startEvent: { type: "any_meaningful" }, returnEvent: { type: "any_meaningful" }, cohort: { type: "start_date" }, visualization: "grid" }; }

export function CardEditorDialog({ open, card, orgId, siteId, filters, catalog, events, funnels, segments, onClose, onSave }: { open: boolean; card?: DashboardCard; orgId: string; siteId: string; filters: DashboardFilters; catalog: AnalyticsCatalog; events: EventDefinitionSummary[]; funnels: FunnelListItem[]; segments: Segment[]; onClose: () => void; onSave: (card: DashboardCard) => void }) {
  const [draft, setDraft] = useState<DashboardCard>(card ?? { title: "Unique users", cardType: "metric", width: "medium", configuration: defaultMetric() });
  const [preview, setPreview] = useState<AnalyticsResponse>(); const [previewError, setPreviewError] = useState<string>();
  const [previewExpanded, setPreviewExpanded] = useState(true);
  const [experiences, setExperiences] = useState<Experience[]>([]);
  useEffect(() => { if (open) experiencesApi.listExperiences(orgId, siteId).then(result => setExperiences(result.experiences)); }, [open, orgId, siteId]);
  useEffect(() => { if (open) { setDraft(card ?? { title: "Unique users", cardType: "metric", width: "medium", configuration: defaultMetric() }); setPreviewExpanded(true); } }, [open, card]);
  const semanticFingerprint = useMemo(() => { const value = structuredClone(draft.configuration) as unknown as Record<string, unknown>; delete value.visualization; delete value.target; return JSON.stringify(value); }, [draft.configuration]);
  useEffect(() => { if (!open || (draft.configuration.kind === "funnel" && !draft.configuration.funnelId) || (draft.configuration.kind === "experience" && !draft.configuration.experienceId)) return; const timer = window.setTimeout(() => { setPreview(undefined); setPreviewError(undefined); analyticsApi.queryAnalytics(orgId, siteId, filters, draft.configuration).then(setPreview).catch((e) => setPreviewError(e instanceof Error ? e.message : "Preview failed")); }, 250); return () => window.clearTimeout(timer); }, [open, orgId, siteId, filters, semanticFingerprint]);
  const valid = draft.title.trim() && !(draft.configuration.kind === "funnel" && !draft.configuration.funnelId) && !(draft.configuration.kind === "experience" && !draft.configuration.experienceId) && !(draft.configuration.kind === "retention" && draft.configuration.cohort.type === "segments" && !draft.configuration.cohort.segmentIds.length);
  return <Dialog open={open} onOpenChange={(next) => !next && onClose()}>
    <DialogContent className="fixed inset-y-0 right-0 left-auto flex h-[100dvh] w-full max-w-[920px] flex-col overflow-hidden translate-x-0 translate-y-0 rounded-l-xl rounded-r-none border-0 bg-background p-0 shadow-[-16px_0_48px_rgba(15,23,42,0.12)] data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=open]:slide-in-from-right data-[state=closed]:slide-out-to-right sm:w-[min(100vw-2rem,920px)]">
      <DialogHeader className="shrink-0 px-5 py-5 pr-12 sm:px-7 sm:py-6">
        <DialogTitle className="text-lg font-medium tracking-[-0.02em] text-foreground">{card ? "Edit card" : "Add card"}</DialogTitle>
        <DialogDescription className="mt-1 max-w-2xl text-xs leading-5 text-muted-foreground">Choose the analysis and presentation for this dashboard view.</DialogDescription>
      </DialogHeader>

      <div className={`grid min-h-0 flex-1 ${previewExpanded ? "lg:grid-cols-[minmax(0,1fr)_minmax(300px,.82fr)]" : "grid-cols-1"}`}>
        <div className="min-h-0 overflow-y-auto px-5 pb-6 sm:px-7">
          <div className="space-y-7">
            <section>
              <div className="mb-3"><p className="text-sm font-medium text-foreground">Analysis</p><p className="mt-0.5 text-xs text-muted-foreground">Select the question this card answers.</p></div>
              <div className="flex flex-wrap gap-1 rounded-lg bg-muted/60 p-1">{([
                { kind: "metric", label: "Metrics" }, { kind: "funnel", label: "Funnel" }, { kind: "retention", label: "Retention" }, { kind: "experience", label: "Experiences" },
              ] as const).map(({ kind, label }) => <Button key={kind} type="button" variant="ghost" className={`h-8 rounded-md px-3 text-xs font-medium ${draft.cardType === kind ? "bg-background text-foreground shadow-sm hover:bg-background" : "text-muted-foreground hover:bg-transparent hover:text-foreground"}`} onClick={() => setDraft({ ...draft, cardType: kind, title: label, configuration: defaultConfig(kind) })}>{label}</Button>)}</div>
            </section>

            <section>
              <p className="mb-3 text-sm font-medium text-foreground">Card details</p>
              <div className="grid gap-4 sm:grid-cols-[minmax(0,1fr)_172px]"><div className="grid gap-2"><Label htmlFor="card-title">Title</Label><Input id="card-title" value={draft.title} onChange={(e) => setDraft({ ...draft, title: e.target.value })} /></div><div className="grid gap-2"><Label>Width</Label><Select value={draft.width} onValueChange={(width: DashboardCard["width"]) => setDraft({ ...draft, width })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="small">Small · 1 column</SelectItem><SelectItem value="medium">Medium · 2 columns</SelectItem><SelectItem value="full">Large · full row</SelectItem></SelectContent></Select></div></div>
            </section>

            <section>
              <div className="mb-4"><p className="text-sm font-medium text-foreground">Configuration</p><p className="mt-0.5 text-xs text-muted-foreground">Refine the data and how it is summarized.</p></div>
              {draft.configuration.kind === "metric" && <MetricFields value={draft.configuration} catalog={catalog} events={events} segments={segments} onChange={(configuration) => setDraft({ ...draft, configuration })} />}
              {draft.configuration.kind === "funnel" && <div className="grid gap-2"><Label>Saved Funnel</Label><Select value={draft.configuration.funnelId || undefined} onValueChange={(funnelId) => setDraft({ ...draft, configuration: { ...draft.configuration as Extract<DashboardCardConfiguration, { kind: "funnel" }>, funnelId } })}><SelectTrigger><SelectValue placeholder="Select a Funnel" /></SelectTrigger><SelectContent>{funnels.map((f) => <SelectItem key={f.id} value={f.id}>{f.name}</SelectItem>)}</SelectContent></Select><p className="text-xs leading-5 text-muted-foreground">Steps and conversion window come from the saved Funnel.</p></div>}
              {draft.configuration.kind === "retention" && <RetentionFields value={draft.configuration} events={events} segments={segments} onChange={(configuration) => setDraft({ ...draft, configuration })} />}
              {draft.configuration.kind === "experience" && <ExperienceFields value={draft.configuration} experiences={experiences} onChange={(configuration) => setDraft({ ...draft, configuration })} />}
            </section>
          </div>
        </div>

        {previewExpanded && <aside className="min-h-0 overflow-y-auto bg-muted/30 px-5 py-5 sm:px-6 sm:py-6">
          <div><p className="text-sm font-medium text-foreground">Preview</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Updates as you change the analysis.</p></div>
          <div className="mt-5 overflow-hidden rounded-xl bg-background"><DashboardCardView card={draft} response={preview} loading={!preview && !previewError} error={previewError} filters={filters} /></div>
        </aside>}
      </div>

      <DialogFooter className="shrink-0 bg-background px-5 py-4 sm:px-7"><Button type="button" variant="ghost" className="mr-auto text-xs text-muted-foreground" aria-expanded={previewExpanded} onClick={() => setPreviewExpanded((expanded) => !expanded)}>{previewExpanded ? "Hide preview" : "Show preview"}</Button><Button variant="ghost" className="text-xs" onClick={onClose}>Cancel</Button><Button className="min-w-24 text-xs" disabled={!valid} onClick={() => onSave({ ...draft, title: draft.title.trim() })}>Save card</Button></DialogFooter>
    </DialogContent>
  </Dialog>;
}

function ExperienceFields({ value, experiences, onChange }: { value: ExperienceCardConfiguration; experiences: Experience[]; onChange: (value: ExperienceCardConfiguration) => void }) {
  const filtered = experiences.filter(experience => value.experienceType === "guide" ? experience.kind === "guide" : value.experienceType === "checklist" ? experience.kind === "checklist" : value.experienceType === "survey" ? experience.widgetType === "survey" : experience.kind === "widget" && experience.widgetType !== "survey");
  const metrics = value.experienceType === "guide" ? [["users_seen", "Users seen"], ["completions", "Completions"], ["completion_rate", "Completion rate"], ["dismissals", "Dismissals"], ["step_reach", "Step reach"], ["step_drop_off", "Step drop-off"]] : value.experienceType === "survey" ? [["users_seen", "Users seen"], ["responses", "Responses"], ["response_rate", "Response rate"], ["abandonment_rate", "Abandonment rate"]] : [["impressions", "Impressions"], ["interactions", "Interactions"], ["interaction_rate", "Interaction rate"], ["dismissals", "Dismissals"]];
  const setType = (experienceType: ExperienceCardConfiguration["experienceType"]) => onChange({ ...value, experienceType, experienceId: "", metric: experienceType === "widget" ? "impressions" : "users_seen", visualization: "total" });
  return <div className="space-y-4"><div className="grid gap-2"><Label>Experience type</Label><Select value={value.experienceType} onValueChange={setType}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="guide">Guide</SelectItem><SelectItem value="checklist">Checklist</SelectItem><SelectItem value="survey">Survey</SelectItem><SelectItem value="widget">Widget</SelectItem></SelectContent></Select></div><div className="grid gap-2"><Label>Experience</Label><Select value={value.experienceId || undefined} onValueChange={experienceId => onChange({ ...value, experienceId })}><SelectTrigger><SelectValue placeholder="Select an experience" /></SelectTrigger><SelectContent>{filtered.map(experience => <SelectItem key={experience.id} value={experience.id}>{experience.name}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2 sm:grid-cols-2"><div className="grid gap-2"><Label>Metric</Label><Select value={value.metric} onValueChange={(metric: ExperienceCardConfiguration["metric"]) => onChange({ ...value, metric, visualization: metric.startsWith("step_") ? "bars" : "total" })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{metrics.map(([id, label]) => <SelectItem key={id} value={id}>{label}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2"><Label>Show as</Label><Select value={value.visualization} onValueChange={(visualization: ExperienceCardConfiguration["visualization"]) => onChange({ ...value, visualization })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{value.metric.startsWith("step_") ? <><SelectItem value="bars">Bars</SelectItem><SelectItem value="horizontal_bars">Horizontal bars</SelectItem><SelectItem value="table">Table</SelectItem></> : <SelectItem value="total">Total</SelectItem>}</SelectContent></Select></div></div></div>;
}

function MetricFields({ value, catalog, events, segments, onChange }: { value: MetricCardConfiguration; catalog: AnalyticsCatalog; events: EventDefinitionSummary[]; segments: Segment[]; onChange: (v: MetricCardConfiguration) => void }) {
  const metric = catalog.metrics.find((m) => m.id === value.metricId)!; const conversion = value.metricId.endsWith("conversion_rate");
  function setMetric(metricId: MetricCardConfiguration["metricId"]) { const isConversion = metricId.endsWith("conversion_rate"); onChange({ ...value, metricId, events: undefined, conversion: isConversion ? { numeratorEvent: events[0]?.name ?? "" } : undefined, breakdown: value.mode === "breakdown" ? value.breakdown : undefined }); }
  function setMode(mode: MetricCardConfiguration["mode"]) { onChange({ ...value, mode, breakdown: mode === "breakdown" ? { dimension: "identity" } : undefined, visualization: mode === "trend" ? "line" : mode === "breakdown" ? "bars" : "total" }); }
  return <div className="space-y-4"><div className="grid gap-2"><Label>Analyze as</Label><Select value={value.metricId} onValueChange={setMetric}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["Users", "Sessions", "Events"].map((group) => <div key={group}><div className="px-2 py-1 text-xs font-semibold text-muted-foreground">{group}</div>{catalog.metrics.filter((m) => m.group === group).map((m) => <SelectItem key={m.id} value={m.id}>{m.label}</SelectItem>)}</div>)}</SelectContent></Select><p className="text-xs text-muted-foreground">{metric.definition}</p></div>
    {conversion ? <div className="grid gap-3 sm:grid-cols-2"><EventSelect label="Numerator event" value={value.conversion?.numeratorEvent ?? ""} events={events} onChange={(numeratorEvent) => onChange({ ...value, conversion: { ...value.conversion!, numeratorEvent } })} /><EventSelect label="Denominator event (optional)" allowNone value={value.conversion?.denominatorEvent ?? "none"} events={events} onChange={(denominatorEvent) => onChange({ ...value, conversion: { ...value.conversion!, denominatorEvent: denominatorEvent === "none" ? undefined : denominatorEvent } })} /></div> : <EventMulti events={events} selected={value.events?.eventNames ?? []} onChange={(eventNames) => onChange({ ...value, events: eventNames.length ? { eventNames, match: value.events?.match ?? "any" } : undefined })} />}
    {!conversion && value.events && <div className="grid gap-2"><Label>Match</Label><Select value={value.events.match} onValueChange={(match: "each" | "any" | "all") => onChange({ ...value, events: { ...value.events!, match } })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{metric.matches.map((match) => <SelectItem key={match} value={match}>{match[0].toUpperCase() + match.slice(1)}</SelectItem>)}</SelectContent></Select></div>}
    <div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label>Result</Label><Select value={value.mode} onValueChange={setMode}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="trend">Trend over time</SelectItem>{metric.breakdowns.length > 0 && <SelectItem value="breakdown">Breakdown</SelectItem>}<SelectItem value="single">Single value</SelectItem></SelectContent></Select></div><VisualizationSelect value={value} onChange={onChange} /></div>
    {value.mode === "breakdown" && <div className="grid gap-2"><Label>Break down by</Label><Select value={value.breakdown?.dimension} onValueChange={(dimension) => onChange({ ...value, breakdown: dimension === "segment" ? { dimension, segmentIds: segments.slice(0, 1).map((s) => s.id) } : dimension === "user_property" ? { dimension, propertyName: "plan" } : { dimension: dimension as Exclude<typeof value.breakdown, undefined>["dimension"] } as any })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{metric.breakdowns.map((d) => <SelectItem key={d} value={d}>{d.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select>{value.breakdown?.dimension === "user_property" && <Input placeholder="Property name" value={value.breakdown.propertyName} onChange={(e) => onChange({ ...value, breakdown: { dimension: "user_property", propertyName: e.target.value } })} />}</div>}
    {value.visualization !== "table" && <div className="rounded-md border p-3"><label className="flex items-center gap-2 text-sm font-medium"><Checkbox checked={Boolean(value.target)} onCheckedChange={(checked) => onChange({ ...value, target: checked ? { value: 100, direction: "at_least", intent: "achieve" } : undefined })} />Add target</label>{value.target && <div className="mt-3 grid gap-2 sm:grid-cols-3"><Input type="number" aria-label="Target value" value={value.target.value} onChange={(e) => onChange({ ...value, target: { ...value.target!, value: Number(e.target.value) } })} /><Select value={value.target.direction} onValueChange={(direction: "at_least" | "at_most") => onChange({ ...value, target: { ...value.target!, direction } })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="at_least">At least</SelectItem><SelectItem value="at_most">At most</SelectItem></SelectContent></Select><Select value={value.target.intent} onValueChange={(intent: "achieve" | "maintain") => onChange({ ...value, target: { ...value.target!, intent } })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="achieve">Achieve</SelectItem><SelectItem value="maintain">Maintain</SelectItem></SelectContent></Select></div>}</div>}
  </div>;
}
function VisualizationSelect({ value, onChange }: { value: MetricCardConfiguration; onChange: (v: MetricCardConfiguration) => void }) { const options = value.mode === "trend" ? [["line", "Line"], ["bars", "Bars"], ["stacked_bars", "Stacked bars"], ["table", "Table"]] : value.mode === "breakdown" ? [["bars", "Vertical bars"], ["horizontal_bars", "Horizontal bars"], ["table", "Table"]] : [["total", "Total period"], ["recent", "Most recent bucket"], ["previous_period", "Previous-period comparison"]]; return <div className="grid gap-2"><Label>Show as</Label><Select value={value.visualization} onValueChange={(visualization: MetricCardConfiguration["visualization"]) => onChange({ ...value, visualization, target: visualization === "table" ? undefined : value.target })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{options.map(([id, label]) => <SelectItem key={id} value={id}>{label}</SelectItem>)}</SelectContent></Select></div>; }
function EventSelect({ label, value, events, allowNone, allowAny, onChange }: { label: string; value: string; events: EventDefinitionSummary[]; allowNone?: boolean; allowAny?: boolean; onChange: (v: string) => void }) { const meaningfulOption = allowAny || label === "Start event" || label === "Return event"; return <div className="grid gap-2"><Label>{label}</Label><Select value={value || undefined} onValueChange={onChange}><SelectTrigger><SelectValue placeholder="Select event" /></SelectTrigger><SelectContent>{allowNone && <SelectItem value="none">Meaningful activity</SelectItem>}{meaningfulOption && <SelectItem value="any">Any meaningful event</SelectItem>}{events.map((e) => <SelectItem key={e.name} value={e.name}>{e.name}</SelectItem>)}</SelectContent></Select></div>; }
function EventMulti({ events, selected, onChange }: { events: EventDefinitionSummary[]; selected: string[]; onChange: (v: string[]) => void }) { const [search, setSearch] = useState(""); const shown = useMemo(() => events.filter((e) => e.name.toLowerCase().includes(search.toLowerCase())).slice(0, 30), [events, search]); return <div className="grid gap-2"><Label>Events (optional)</Label><div className="relative"><Search className="absolute left-2.5 top-2.5 size-4 text-muted-foreground" /><Input className="pl-8" placeholder="Search events" value={search} onChange={(e) => setSearch(e.target.value)} /></div><div className="max-h-32 overflow-y-auto rounded-md border p-2">{shown.map((event) => <label key={event.name} className="flex items-center gap-2 py-1 text-sm"><Checkbox checked={selected.includes(event.name)} disabled={!selected.includes(event.name) && selected.length >= 10} onCheckedChange={(checked) => onChange(checked ? [...selected, event.name] : selected.filter((v) => v !== event.name))} />{event.name}</label>)}</div></div>; }
function RetentionFields({ value, events, segments, onChange }: { value: Extract<DashboardCardConfiguration, { kind: "retention" }>; events: EventDefinitionSummary[]; segments: Segment[]; onChange: (v: Extract<DashboardCardConfiguration, { kind: "retention" }>) => void }) { const eventValue = (ref: typeof value.startEvent) => ref.type === "any_meaningful" ? "any" : ref.eventName; const ref = (v: string) => v === "any" ? { type: "any_meaningful" as const } : { type: "event" as const, eventName: v }; return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><EventSelect label="Start event" value={eventValue(value.startEvent)} events={events} onChange={(v) => onChange({ ...value, startEvent: ref(v) })} /><EventSelect label="Return event" value={eventValue(value.returnEvent)} events={events} onChange={(v) => onChange({ ...value, returnEvent: ref(v) })} /></div><div className="grid gap-2"><Label>Cohorts</Label><Select value={value.cohort.type} onValueChange={(type) => onChange({ ...value, cohort: type === "start_date" ? { type } : { type: "segments", segmentIds: segments.slice(0, 1).map((s) => s.id) } })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="start_date">Start-event date</SelectItem><SelectItem value="segments">Current Segment comparisons</SelectItem></SelectContent></Select>{value.cohort.type === "segments" && <div className="max-h-32 overflow-y-auto rounded border p-2">{segments.map((s) => <label key={s.id} className="flex gap-2 py-1 text-sm"><Checkbox checked={value.cohort.type === "segments" && value.cohort.segmentIds.includes(s.id)} onCheckedChange={(checked) => { if (value.cohort.type !== "segments") return; const ids = checked ? [...value.cohort.segmentIds, s.id].slice(0, 10) : value.cohort.segmentIds.filter((id) => id !== s.id); onChange({ ...value, cohort: { type: "segments", segmentIds: ids } }); }} />{s.name}</label>)}</div>}</div><div className="grid gap-2"><Label>View</Label><Select value={value.visualization} onValueChange={(visualization: "grid" | "trend") => onChange({ ...value, visualization })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="grid">Cohort grid</SelectItem><SelectItem value="trend">Retention trend</SelectItem></SelectContent></Select></div></div>; }
