import { AlertCircle, RefreshCw } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ReferenceLine, XAxis, YAxis } from "recharts";
import { DashboardCardFooter, DashboardCardHeader } from "@/components/dashboard/DashboardCardChrome";
import { Button } from "@movecues/ui";
import { Card, CardContent } from "@movecues/ui";
import { ChartContainer, ChartTooltip, ChartTooltipContent } from "@/components/ui/chart";
import { Skeleton } from "@movecues/ui";
import type { AnalyticsResponse, DashboardCard, DashboardFilters } from "@/types/api";
import { cn } from "@movecues/ui";
import { chartAxisTick, chartMargin, formatTooltipDate, getResponsiveDateAxisProps, getResponsiveTickProps } from "@/lib/chartFormatting";

const COLORS = ["#2563eb", "#0d9488", "#9333ea", "#ea580c", "#db2777", "#4f46e5", "#65a30d", "#0891b2", "#b45309", "#475569"];
const chartGrid = <CartesianGrid stroke="hsl(var(--border))" strokeDasharray="3 6" vertical={false} opacity={0.7} />;
const gradientId = (card: DashboardCard, key: string) => `dashboard-chart-${card.id ?? card.title}-${key}`.replace(/[^a-zA-Z0-9_-]/g, "-");
/** Board grid: small occupies one lane, medium two, and full the entire four-lane row. */
export function cardWidthClass(width: DashboardCard["width"]) { return width === "small" ? "xl:col-span-1" : width === "medium" ? "xl:col-span-2" : "xl:col-span-4"; }

export function DashboardCardView({ card, response, loading, error, editable, draggable, summary, onDragStart, onDragOver, onDrop, onRetry, onEdit, onDuplicate, onDelete, onMove, onDrilldown }: { card: DashboardCard; response?: AnalyticsResponse; loading?: boolean; error?: string; filters: DashboardFilters; editable?: boolean; draggable?: boolean; summary?: boolean; onDragStart?: () => void; onDragOver?: () => void; onDrop?: () => void; onRetry?: () => void; onEdit?: () => void; onDuplicate?: () => void; onDelete?: () => void; onMove?: (delta: number) => void; onDrilldown?: () => void }) {
  return <Card draggable={draggable} onDragStart={onDragStart} onDragOver={(event) => { if (draggable) event.preventDefault(); onDragOver?.(); }} onDrop={(event) => { if (draggable) event.preventDefault(); onDrop?.(); }} className={cn("min-w-0 border-border/80 bg-gradient-to-b from-card to-card/90 shadow-sm transition-[box-shadow,transform]", summary ? "h-fit w-full max-w-[240px] justify-self-center border-primary/10 bg-gradient-to-br from-card via-card to-primary/[0.035]" : cardWidthClass(card.width), draggable && "cursor-grab active:cursor-grabbing hover:-translate-y-0.5 hover:shadow-lg")}>
    <DashboardCardHeader title={card.title} definition={response?.metadata.definition} editable={editable} onEdit={onEdit} onDuplicate={onDuplicate} onDelete={onDelete} onMove={onMove} />
    <CardContent className={cn("px-5 pt-0", summary ? "pb-3" : "pb-4")}>{loading ? <div className="space-y-3"><Skeleton className="h-8 w-32" /><Skeleton className={cn("w-full", summary ? "h-14" : "h-48")} /></div> : error ? <div className={cn("flex flex-col items-center justify-center gap-3 text-center", summary ? "min-h-20" : "min-h-40")}><AlertCircle className="size-6 text-destructive" /><p className="text-sm text-muted-foreground">{error}</p><Button size="sm" variant="outline" onClick={onRetry}><RefreshCw />Retry</Button></div> : response ? <ResultView card={card} response={response} summary={summary} /> : <div className={cn("flex items-center justify-center text-sm text-muted-foreground", summary ? "min-h-20" : "min-h-40")}>No data yet.</div>}</CardContent>
    <DashboardCardFooter dataFreshness={response?.metadata.dataFreshness} canDrilldown={Boolean(response?.metadata.drilldown.length)} onDrilldown={onDrilldown} />
  </Card>;
}

function ResultView({ card, response, summary }: { card: DashboardCard; response: AnalyticsResponse; summary?: boolean }) {
  const result = response.result;
  if (result.kind === "scalar") return <div className={cn("flex flex-wrap items-center gap-8", summary ? "min-h-20 w-full justify-center text-center" : "min-h-40")}>{result.values.map((v) => { const visualization = card.configuration.kind === "metric" ? card.configuration.visualization : "total"; const shown = visualization === "recent" ? v.recentValue : v.value; return <div key={v.seriesKey}><div className={cn("font-semibold tracking-tight tabular-nums", summary ? "bg-gradient-to-br from-foreground to-foreground/70 bg-clip-text text-5xl text-transparent" : "text-4xl")}>{formatValue(shown, card)}</div>{visualization === "previous_period" && <div className={cn("mt-1 text-sm", (v.deltaPercent ?? 0) >= 0 ? "text-emerald-600" : "text-red-600")}>{v.deltaPercent === null ? "No prior value" : `${v.deltaPercent >= 0 ? "+" : ""}${v.deltaPercent}% vs previous`}</div>}</div>; })}</div>;
  if (result.kind === "breakdown") {
    if (!result.rows.length) return <Empty />;
    if (card.configuration.kind === "metric" && card.configuration.visualization === "table") return <table className="w-full text-sm"><thead><tr><th className="pb-2 text-left">Group</th><th className="pb-2 text-right">Value</th></tr></thead><tbody>{result.rows.map((r) => <tr key={r.key} className="border-t"><td className="py-2">{r.label}</td><td className="py-2 text-right font-mono">{r.value.toLocaleString()}</td></tr>)}</tbody></table>;
    return <ChartContainer config={{ value: { label: "Value", color: COLORS[0] } }}><BarChart data={result.rows} layout={card.configuration.kind === "metric" && card.configuration.visualization === "horizontal_bars" ? "vertical" : "horizontal"} margin={chartMargin}>{chartGrid}<XAxis dataKey={card.configuration.kind === "metric" && card.configuration.visualization === "horizontal_bars" ? "value" : "label"} type={card.configuration.kind === "metric" && card.configuration.visualization === "horizontal_bars" ? "number" : "category"} tickLine={false} axisLine={false} tick={chartAxisTick} tickMargin={8} /><YAxis dataKey="label" type={card.configuration.kind === "metric" && card.configuration.visualization === "horizontal_bars" ? "category" : "number"} hide={card.configuration.kind === "metric" && card.configuration.visualization !== "horizontal_bars"} width={100} tickLine={false} axisLine={false} tick={chartAxisTick} tickMargin={8} /><ChartTooltip cursor={{ fill: "hsl(var(--muted) / 0.45)" }} content={<ChartTooltipContent />} /><Bar dataKey="value" fill={COLORS[0]} maxBarSize={44} radius={[6, 6, 2, 2]} /></BarChart></ChartContainer>;
  }
  if (result.kind === "timeseries") {
    if (!result.buckets.some((b) => Object.values(b.values).some(Boolean))) return <Empty />;
    const data = result.buckets.map((b) => ({ label: b.label, ...b.values })); const config = Object.fromEntries(result.series.map((s, i) => [s.key, { label: s.label, color: COLORS[i] }]));
    if (card.configuration.kind === "metric" && card.configuration.visualization === "table") return <table className="w-full text-sm"><thead><tr><th className="text-left">Period</th>{result.series.map((s) => <th key={s.key} className="text-right">{s.label}</th>)}</tr></thead><tbody>{data.map((row) => <tr key={row.label as string} className="border-t"><td className="py-2">{row.label as string}</td>{result.series.map((s) => <td key={s.key} className="text-right font-mono">{Number((row as Record<string, string | number>)[s.key] ?? 0).toLocaleString()}</td>)}</tr>)}</tbody></table>;
    const bars = card.configuration.kind === "metric" && ["bars", "stacked_bars"].includes(card.configuration.visualization);
    return <ChartContainer config={config}>{({ width }) => { const dateAxis = getResponsiveDateAxisProps(data.map((row) => row.label), width); const tooltip = <ChartTooltip cursor={{ stroke: "hsl(var(--border))", strokeDasharray: "3 3" }} content={<ChartTooltipContent labelFormatter={formatTooltipDate} />} />; return bars ? <BarChart data={data} margin={chartMargin}>{chartGrid}<XAxis dataKey="label" tickLine={false} axisLine={false} {...dateAxis} /><YAxis tickLine={false} axisLine={false} tick={chartAxisTick} tickMargin={8} />{tooltip}{result.series.map((s, i) => <Bar key={s.key} dataKey={s.key} fill={COLORS[i]} maxBarSize={44} stackId={card.configuration.kind === "metric" && card.configuration.visualization === "stacked_bars" ? "value" : undefined} radius={[5, 5, 1, 1]} />)}{card.configuration.kind === "metric" && card.configuration.target && <ReferenceLine y={card.configuration.target.value} stroke="#dc2626" strokeDasharray="4 4" />}</BarChart> : <AreaChart data={data} margin={chartMargin}><defs>{result.series.map((s, i) => <linearGradient key={s.key} id={gradientId(card, s.key)} x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor={COLORS[i]} stopOpacity={0.3} /><stop offset="100%" stopColor={COLORS[i]} stopOpacity={0.015} /></linearGradient>)}</defs>{chartGrid}<XAxis dataKey="label" tickLine={false} axisLine={false} {...dateAxis} /><YAxis tickLine={false} axisLine={false} tick={chartAxisTick} tickMargin={8} />{tooltip}{result.series.map((s, i) => <Area key={s.key} type="monotone" dataKey={s.key} stroke={COLORS[i]} strokeWidth={2.5} fill={`url(#${gradientId(card, s.key)})`} dot={false} activeDot={{ r: 4, fill: COLORS[i], stroke: "hsl(var(--card))", strokeWidth: 2 }} />)}{card.configuration.kind === "metric" && card.configuration.target && <ReferenceLine y={card.configuration.target.value} stroke="#dc2626" strokeDasharray="4 4" />}</AreaChart>; }}</ChartContainer>;
  }
  if (result.kind === "funnel") { const max = result.steps[0]?.users || 1; return <div className="space-y-3">{result.steps.map((step) => <div key={step.index}><div className="mb-1 flex justify-between text-xs"><span>{step.label}</span><span>{step.users.toLocaleString()} · {step.conversionFromStart}%</span></div><div className="flex h-8 overflow-hidden rounded bg-muted" style={{ width: `${Math.max(12, step.users / max * 100)}%` }}><div className="bg-blue-600" style={{ width: `${step.users ? (step.users - step.droppedBeforeNext) / step.users * 100 : 0}%` }} /><div className="bg-blue-200" style={{ flex: 1 }} /></div></div>)}</div>; }
  if (!result.rows.length) return <Empty />;
  if (card.configuration.kind === "retention" && card.configuration.visualization === "trend") { const keys = result.rows.map((r) => r.key); const trendAxis = getResponsiveTickProps(result.trend.length); return <ChartContainer config={Object.fromEntries(keys.map((k, i) => [k, { label: result.rows[i].label, color: COLORS[i] }]))}><AreaChart data={result.trend.map((p) => ({ label: p.label, ...p.values }))} margin={chartMargin}><defs>{keys.map((key, i) => <linearGradient key={key} id={gradientId(card, key)} x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor={COLORS[i]} stopOpacity={0.24} /><stop offset="100%" stopColor={COLORS[i]} stopOpacity={0.01} /></linearGradient>)}</defs>{chartGrid}<XAxis dataKey="label" tickLine={false} axisLine={false} tick={chartAxisTick} {...trendAxis} /><YAxis domain={[0, 100]} tickLine={false} axisLine={false} tick={chartAxisTick} tickMargin={8} /><ChartTooltip cursor={{ stroke: "hsl(var(--border))", strokeDasharray: "3 3" }} content={<ChartTooltipContent />} />{keys.map((key, i) => <Area key={key} type="monotone" dataKey={key} stroke={COLORS[i]} strokeWidth={2.25} fill={`url(#${gradientId(card, key)})`} dot={false} activeDot={{ r: 4, fill: COLORS[i], stroke: "hsl(var(--card))", strokeWidth: 2 }} />)}</AreaChart></ChartContainer>; }
  return <div className="overflow-x-auto"><table className="w-full min-w-max text-xs"><thead><tr><th className="p-2 text-left">Cohort</th><th className="p-2 text-right">Size</th>{result.rows[0].cells.map((c) => <th key={c.offset} className="p-2 text-right">{c.label}</th>)}</tr></thead><tbody>{result.rows.map((row) => <tr key={row.key} className="border-t"><td className="p-2 font-medium">{row.label}{row.smallCohort && <span className="ml-1 text-amber-600" title="Small cohort">⚠</span>}</td><td className="p-2 text-right">{row.size}</td>{row.cells.map((cell) => <td key={cell.offset} className={cn("p-2 text-right", cell.incomplete && "opacity-45")} style={{ backgroundColor: `rgba(37,99,235,${Math.max(.05, cell.percentage / 125)})` }}>{cell.percentage}%</td>)}</tr>)}</tbody></table>{result.rows.some((r) => r.currentSegmentComparison) && <p className="mt-2 text-xs text-muted-foreground">Current Segment comparison; membership is not historical.</p>}</div>;
}
function formatValue(value: number, card: DashboardCard) { if ((card.configuration.kind === "metric" && (card.configuration.metricId.includes("rate") || card.configuration.metricId === "users.stickiness")) || (card.configuration.kind === "experience" && card.configuration.metric.includes("rate"))) return `${value}%`; if (card.configuration.kind === "metric" && card.configuration.metricId === "sessions.observed_duration") return `${Math.round(value / 1000)}s`; return value.toLocaleString(); }
function Empty() { return <div className="flex min-h-40 items-center justify-center text-sm text-muted-foreground">No matching analytics in this range.</div>; }
