import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { beforeEach, describe, expect, it, vi } from "vitest";
import * as workspace from "../../auth/WorkspaceContext";
import * as experiencesApi from "../../api/experiences"; import * as pagesApi from "../../api/pages"; import * as segmentsApi from "../../api/segments"; import * as eventsApi from "../../api/events";
import { Sidebar } from "../../components/Sidebar";
import { CreateExperienceModal } from "./CreateExperienceModal"; import { ExperienceListPage } from "./ExperienceListPage"; import { ExperienceEditorPage } from "./ExperienceEditorPage";
import type { Experience } from "../../types/experiences";

vi.mock("../../auth/WorkspaceContext"); vi.mock("../../api/experiences"); vi.mock("../../api/pages"); vi.mock("../../api/segments"); vi.mock("../../api/events");
const builderHarness=vi.hoisted(()=>({flush:vi.fn()}));
vi.mock("../../components/experiences/GrapesWidgetBuilder",async()=>{const React=await import("react");return{GrapesWidgetBuilder:React.forwardRef(function Builder({onChange}:{onChange:(value:unknown)=>void},ref){React.useImperativeHandle(ref,()=>({flush:builderHarness.flush}));return <button onClick={()=>onChange({builder:{version:1,projectData:{pages:[]},html:'<section class="loopz-widget"><h2 data-loopz-content="heading">Latest heading</h2></section>',css:".loopz-widget{}"},content:{heading:"Latest heading",body:"World"}})}>Change builder</button>;})}});
const mockedWorkspace=vi.mocked(workspace); const mockedExperiences=vi.mocked(experiencesApi); const mockedPages=vi.mocked(pagesApi); const mockedSegments=vi.mocked(segmentsApi); const mockedEvents=vi.mocked(eventsApi);
const page={id:"pg_1",siteId:"site_1",name:"Home",description:null,area:null,pageType:null,rules:[{id:"r1",kind:"include" as const,operator:"equals" as const,value:"/home"}],heatmapEnabled:false,views:0,uniqueVisitors:0,uniqueSessions:0,lastSeenAt:null,createdAt:"2026-01-01",updatedAt:"2026-01-01"};
const definition={content:{heading:"Hello",body:"World"},design:{width:"md" as const,theme:{background:"#ffffff",foreground:"#111827",primary:"#2563eb",borderRadius:"md" as const}},behavior:{dismissible:true,toastPosition:"bottom-right" as const},targeting:{pageRules:[],audience:{type:"all" as const},trigger:{type:"page_load" as const},frequency:{mode:"once" as const},priority:0}};
const experience:Experience={id:"exp_1",siteId:"site_1",kind:"widget",widgetType:"anchored_card",name:"Welcome",status:"draft",buildPageId:"pg_1",buildUrl:"https://app.example.com/home",publishedVersionId:null,createdBy:"u1",createdAt:"2026-01-01",updatedAt:"2026-01-01",draftVersion:{id:"v1",experienceId:"exp_1",versionNumber:1,state:"draft",definition,createdBy:"u1",createdAt:"2026-01-01",publishedAt:null},publishedVersion:null};
function ready(){mockedWorkspace.useWorkspace.mockReturnValue({orgs:[],currentOrg:{orgId:"org_1",name:"Acme",role:"OWNER"},setCurrentOrgId:vi.fn(),sites:[],currentSite:{id:"site_1",siteId:"public_1",name:"App",domain:"app.example.com"},setCurrentSiteId:vi.fn(),loading:false,error:null,refreshSites:vi.fn()}); mockedPages.listPages.mockResolvedValue({pages:[page]});}

describe("Experiences dashboard",()=>{
  beforeEach(()=>{vi.clearAllMocks();ready();mockedSegments.listSegments.mockResolvedValue({segments:[],total:0,limit:100,offset:0});mockedEvents.listEvents.mockResolvedValue({events:[],total:0,limit:100,offset:0});vi.spyOn(window,"open").mockReturnValue({location:{href:""},close:vi.fn()} as unknown as Window);});
  it("renders the experience collection routes without generic widgets or visual builder",()=>{render(<MemoryRouter><Sidebar onOpenSettings={vi.fn()}/></MemoryRouter>);expect(screen.getByRole("link",{name:"Guides"})).toHaveAttribute("href","/experiences/guides");expect(screen.getByRole("link",{name:"Modals"})).toHaveAttribute("href","/experiences/modals");expect(screen.getByRole("link",{name:"Tooltips"})).toHaveAttribute("href","/experiences/tooltips");expect(screen.getByRole("link",{name:"Banners"})).toHaveAttribute("href","/experiences/banners");expect(screen.getByRole("link",{name:"Checklists"})).toHaveAttribute("href","/experiences/checklists");expect(screen.queryByRole("link",{name:"Widgets"})).not.toBeInTheDocument();expect(screen.queryByRole("link",{name:"Visual Builder"})).not.toBeInTheDocument();});
  it("filters each supported collection and isolates unsupported checklists",async()=>{mockedExperiences.listExperiences.mockResolvedValue({experiences:[]});const {rerender}=render(<MemoryRouter><ExperienceListPage kind="guide"/></MemoryRouter>);expect(await screen.findByText("Create your first guide.")).toBeInTheDocument();expect(mockedExperiences.listExperiences).toHaveBeenLastCalledWith("org_1","site_1","guide",undefined);rerender(<MemoryRouter><ExperienceListPage kind="widget" widgetType="modal" singularLabel="modal" pluralLabel="Modals"/></MemoryRouter>);expect(await screen.findByText("Create your first modal.")).toBeInTheDocument();expect(mockedExperiences.listExperiences).toHaveBeenLastCalledWith("org_1","site_1","widget","modal");rerender(<MemoryRouter><ExperienceListPage kind="widget" singularLabel="checklist" pluralLabel="Checklists" unsupported/></MemoryRouter>);expect(await screen.findByText("Checklists are not available yet.")).toBeInTheDocument();});
  it("creates a modal without exposing a generic widget selector or changing build-page targeting",async()=>{mockedExperiences.createExperience.mockResolvedValue(experience);mockedExperiences.createEditorSession.mockResolvedValue({sessionId:"ees",launchUrl:"https://app.example.com/home?loopz_editor_token=x",expiresAt:"2026-01-01"});render(<MemoryRouter><CreateExperienceModal kind="widget" widgetType="modal" singularLabel="modal" open onOpenChange={vi.fn()}/></MemoryRouter>);await screen.findByRole("option",{name:"Home"});expect(screen.queryByLabelText("Widget type")).not.toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Open visual editor"}));await waitFor(()=>expect(mockedExperiences.createExperience).toHaveBeenCalledWith("org_1","site_1",expect.objectContaining({widgetType:"modal",buildPageId:"pg_1",useBuildPageAsTarget:false})));expect(mockedExperiences.createExperience.mock.calls[0][2]).not.toHaveProperty("definition");});
  it("cancel creates no record and a manual URL outside the site is rejected",async()=>{const onOpen=vi.fn();render(<MemoryRouter><CreateExperienceModal kind="guide" open onOpenChange={onOpen}/></MemoryRouter>);await screen.findByRole("option",{name:"Home"});fireEvent.change(screen.getByLabelText("Build on page"),{target:{value:"manual"}});fireEvent.change(screen.getByLabelText("Page URL"),{target:{value:"https://evil.example.com"}});fireEvent.click(screen.getByRole("button",{name:"Open visual editor"}));expect(await screen.findByText(/configured domain/i)).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Cancel"}));expect(mockedExperiences.createExperience).not.toHaveBeenCalled();expect(onOpen).toHaveBeenCalledWith(false);});
  it("surfaces target-required publication validation from the draft/publish UI",async()=>{mockedExperiences.getExperience.mockResolvedValue(experience);mockedExperiences.updateExperience.mockResolvedValue(experience);mockedExperiences.publishExperience.mockRejectedValue(new Error("target_required"));render(<MemoryRouter initialEntries={["/experiences/exp_1/edit"]}><Routes><Route path="/experiences/:experienceId/edit" element={<ExperienceEditorPage/>}/></Routes></MemoryRouter>);expect(await screen.findByText("Welcome")).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Publish"}));expect(await screen.findByText(/every guide step/i)).toBeInTheDocument();});
  it("shows Builder only for widgets while preserving stable tabs",async()=>{mockedExperiences.getExperience.mockResolvedValue(experience);render(<MemoryRouter initialEntries={["/experiences/exp_1/edit"]}><Routes><Route path="/experiences/:experienceId/edit" element={<ExperienceEditorPage/>}/></Routes></MemoryRouter>);expect(await screen.findByRole("tab",{name:"Builder"})).toBeInTheDocument();expect(screen.queryByRole("tab",{name:"Content"})).not.toBeInTheDocument();expect(screen.queryByRole("tab",{name:"Design"})).not.toBeInTheDocument();expect(screen.getByRole("tab",{name:"Behavior"})).toBeInTheDocument();expect(screen.getByRole("tab",{name:"Targeting"})).toBeInTheDocument();expect(screen.getByRole("tab",{name:"Publish"})).toBeInTheDocument();});
  it("flushes the latest builder edit before publishing",async()=>{mockedExperiences.getExperience.mockResolvedValue(experience);mockedExperiences.updateExperience.mockResolvedValue(experience);mockedExperiences.publishExperience.mockResolvedValue(experience);render(<MemoryRouter initialEntries={["/experiences/exp_1/edit"]}><Routes><Route path="/experiences/:experienceId/edit" element={<ExperienceEditorPage/>}/></Routes></MemoryRouter>);fireEvent.click(await screen.findByRole("button",{name:"Change builder"}));fireEvent.click(screen.getByRole("button",{name:"Publish"}));await waitFor(()=>expect(mockedExperiences.publishExperience).toHaveBeenCalled());expect(mockedExperiences.updateExperience.mock.calls[0][3]).toMatchObject({definition:{builder:{version:1,html:expect.stringContaining("Latest heading")},content:{heading:"Latest heading"}}});expect(mockedExperiences.updateExperience.mock.invocationCallOrder[0]).toBeLessThan(mockedExperiences.publishExperience.mock.invocationCallOrder[0]);});
  it("flushes and saves the latest builder edit before creating a live-preview session",async()=>{mockedExperiences.getExperience.mockResolvedValue(experience);mockedExperiences.updateExperience.mockResolvedValue(experience);mockedExperiences.createEditorSession.mockResolvedValue({sessionId:"ees",launchUrl:"https://app.example.com/home?loopz_editor_token=token",expiresAt:"2026-01-01"});render(<MemoryRouter initialEntries={["/experiences/exp_1/edit"]}><Routes><Route path="/experiences/:experienceId/edit" element={<ExperienceEditorPage/>}/></Routes></MemoryRouter>);fireEvent.click(await screen.findByRole("button",{name:"Change builder"}));fireEvent.click(screen.getByRole("button",{name:"Open live editor"}));await waitFor(()=>expect(mockedExperiences.createEditorSession).toHaveBeenCalled());expect(builderHarness.flush).toHaveBeenCalled();expect(mockedExperiences.updateExperience.mock.calls[0][3]).toMatchObject({definition:{builder:{html:expect.stringContaining("Latest heading")}}});expect(mockedExperiences.updateExperience.mock.invocationCallOrder[0]).toBeLessThan(mockedExperiences.createEditorSession.mock.invocationCallOrder[0]);expect(window.open).toHaveBeenCalledWith("https://app.example.com/home?loopz_editor_token=token","_blank");});
  it("keeps the existing Content and Design editor and preview step parameter for guides",async()=>{const guide={...experience,kind:"guide" as const,widgetType:null,name:"Guide",draftVersion:{...experience.draftVersion!,definition:{steps:[{id:"step_1",content:{heading:"Step",body:"Body"},behavior:{placement:"auto" as const,alignment:"center" as const,offset:8,dismissible:true}}],design:definition.design,targeting:definition.targeting}}};mockedExperiences.getExperience.mockResolvedValue(guide);mockedExperiences.updateExperience.mockResolvedValue(guide);mockedExperiences.createEditorSession.mockResolvedValue({sessionId:"ees",launchUrl:"https://app.example.com/home?loopz_editor_token=token",expiresAt:"2026-01-01"});render(<MemoryRouter initialEntries={["/experiences/exp_1/edit"]}><Routes><Route path="/experiences/:experienceId/edit" element={<ExperienceEditorPage/>}/></Routes></MemoryRouter>);expect(await screen.findByRole("tab",{name:"Content"})).toBeInTheDocument();expect(screen.getByRole("tab",{name:"Design"})).toBeInTheDocument();expect(screen.queryByRole("tab",{name:"Builder"})).not.toBeInTheDocument();expect(screen.getByText(/Editing step 1 of 1/)).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Open live editor"}));await waitFor(()=>expect(window.open).toHaveBeenCalledWith("https://app.example.com/home?loopz_editor_token=token&loopz_editor_step=0","_blank"));});
});
