import { Tabs, TabsContent, TabsList, TabsTrigger } from "@movecues/ui";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@movecues/ui";
import type { SessionEpisodeViewModel } from "./sessionTimeline";
import { elapsedLabel, episodeSummary } from "./sessionTimeline";

export function SessionNavigator({ episodes, density, durationMs, activeEpisodeId, onSelect }: { episodes: SessionEpisodeViewModel[]; density: number[]; durationMs: number; activeEpisodeId: string | null; onSelect: (id: string) => void }) {
  const maxDensity = Math.max(...density, 1);
  return <aside className="xl:sticky xl:top-8 xl:self-start"><div className="rounded-lg border bg-card p-4"><Tabs defaultValue="timeline"><TabsList className="grid w-full grid-cols-2"><TabsTrigger value="timeline">Timeline</TabsTrigger><TabsTrigger value="episodes">Episodes</TabsTrigger></TabsList><TabsContent value="timeline" className="mt-4"><div className="flex justify-between mono text-[10px] text-muted-foreground"><span>0:00</span><span>{elapsedLabel(durationMs)}</span></div><TooltipProvider><div className="mt-1 flex h-10 items-end gap-px border-x border-b px-1 pb-1" aria-label="Visible recorded evidence density">{density.map((count, index) => <Tooltip key={index}><TooltipTrigger asChild><span className="min-w-0 flex-1 rounded-[1px] bg-primary/60" style={{ height: count ? `${Math.max(12, (count / maxDensity) * 100)}%` : "2px" }} aria-label={`${count} visible events around ${elapsedLabel((index + .5) / density.length * durationMs)}`} /></TooltipTrigger><TooltipContent>{count} visible event{count === 1 ? "" : "s"} around {elapsedLabel((index + .5) / density.length * durationMs)}</TooltipContent></Tooltip>)}</div></TooltipProvider><div className="mt-5 space-y-0">{episodes.map((episode, index) => <TimelineRow key={episode.id} episode={episode} active={episode.id === activeEpisodeId} last={index === episodes.length - 1} onSelect={onSelect} />)}<div className="ml-[3px] mt-1 flex items-center gap-3 text-xs text-muted-foreground"><span className="mono w-9">{elapsedLabel(durationMs)}</span><span>End</span></div></div></TabsContent><TabsContent value="episodes" className="mt-3"><ol className="space-y-1">{episodes.map((episode) => <li key={episode.id}><button type="button" className={`w-full rounded-md px-2 py-2 text-left text-xs transition-colors hover:bg-muted ${episode.id === activeEpisodeId ? "bg-primary/[0.06]" : ""}`} onClick={() => onSelect(episode.id)}><div className="flex gap-2"><span className="mono text-muted-foreground">{String(episode.index + 1).padStart(2, "0")}</span><span className="min-w-0 flex-1"><span className="block font-medium text-foreground">{episode.title}</span><span className="block text-muted-foreground">{elapsedLabel(episode.displayStartMs)} – {elapsedLabel(episode.displayEndMs)}</span><span className="mt-0.5 block text-muted-foreground">{episodeSummary(episode)}</span></span></div></button></li>)}</ol></TabsContent></Tabs></div></aside>;
}
function TimelineRow({ episode, active, last, onSelect }: { episode: SessionEpisodeViewModel; active: boolean; last: boolean; onSelect: (id: string) => void }) { return <button type="button" onClick={() => onSelect(episode.id)} className="group flex w-full gap-2 text-left"><span className="mono w-9 pt-0.5 text-[10px] text-muted-foreground">{elapsedLabel(episode.displayStartMs)}</span><span className="relative flex w-3 justify-center">{!last && <span className="absolute top-3 h-[calc(100%+8px)] border-l border-border" />}<span className={`relative z-10 mt-1.5 size-2 rounded-full border ${active ? "border-primary bg-primary" : "border-muted-foreground/50 bg-card group-hover:border-primary"}`} /></span><span className={`min-w-0 flex-1 pb-4 text-xs ${active ? "text-foreground" : "text-muted-foreground"}`}><span className="block font-medium text-foreground">{episode.title}</span><span>{elapsedLabel(episode.displayStartMs)} – {elapsedLabel(episode.displayEndMs)}</span></span></button>; }
