import { BarChart3, BookOpen, CheckSquare, ChevronDown, FileText, Flame, Gauge, Info, LayoutTemplate, MousePointerClick, Network, PanelLeftClose, Settings, Sparkles, Users, Waypoints, X } from "lucide-react";
import type { ComponentType } from "react";
import { NavLink } from "react-router-dom";
import { useWorkspace } from "@/auth/WorkspaceContext";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import type { SettingsSection } from "./settings/SettingsModal";
interface NavItem { label:string; path?:string; disabled?:boolean; icon:ComponentType<{className?:string}> } interface NavSection { label:string; items:NavItem[] }
const SECTIONS:NavSection[]=[
  {label:"Workspace",items:[{label:"Overview",disabled:true,icon:Gauge}]},
  {label:"Experiences",items:[{label:"Guides",path:"/experiences/guides",icon:BookOpen},{label:"Widgets",path:"/experiences/widgets",icon:LayoutTemplate},{label:"Visual Builder",path:"/experiences/builder",icon:Sparkles},{label:"Modals",path:"/experiences/modals",icon:LayoutTemplate},{label:"Tooltips",path:"/experiences/tooltips",icon:Info},{label:"Banners",path:"/experiences/banners",icon:BarChart3},{label:"Checklists",path:"/experiences/checklists",icon:CheckSquare}]},
  {label:"Observe",items:[{label:"Pages",path:"/observe/pages",icon:FileText},{label:"Sessions",path:"/observe/sessions",icon:MousePointerClick},{label:"Events",path:"/observe/events",icon:Waypoints},{label:"Funnels",path:"/observe/funnels",icon:Network},/* Replay stays disabled until its route is restored. */{label:"Heatmaps",path:"/observe/heatmaps",icon:Flame}]},
  {label:"People",items:[{label:"Users",path:"/users",icon:Users},{label:"Segments",path:"/segments",icon:PanelLeftClose}]},
];
export function Sidebar({onOpenSettings,mobileOpen=false,onMobileClose}:{onOpenSettings:(section?:SettingsSection)=>void;mobileOpen?:boolean;onMobileClose?:()=>void}) {
  const {currentOrg,currentSite}=useWorkspace();
  const content=<aside className="flex h-full flex-col bg-[#fafafa] p-3"><div className="flex h-11 items-center gap-2 px-2"><div className="grid size-7 place-items-center rounded-md bg-foreground text-xs font-bold text-background">L</div><span className="text-sm font-semibold">Loopz</span>{onMobileClose&&<Button variant="ghost" size="icon" className="ml-auto lg:hidden" onClick={onMobileClose} aria-label="Close navigation"><X/></Button>}</div>
    <button type="button" onClick={()=>onOpenSettings("sites")} className="mt-2 flex w-full items-center gap-2 rounded-md border bg-white px-2.5 py-2 text-left shadow-sm transition-colors hover:bg-accent focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/20"><span className="grid size-6 shrink-0 place-items-center rounded-sm bg-secondary text-[10px] font-semibold">{currentOrg?.name?.slice(0,1).toUpperCase()??"W"}</span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-medium">{currentOrg?.name??"Workspace"}</span><span className="block truncate text-[10px] text-muted-foreground">{currentSite?.domain??"Select a site"}</span></span><ChevronDown className="size-3.5 text-muted-foreground"/></button>
    <nav className="mt-5 flex-1 space-y-5 overflow-y-auto" aria-label="Main navigation">{SECTIONS.map(section=><div key={section.label}><div className="mb-1 px-2 text-[10px] font-semibold uppercase text-muted-foreground">{section.label}</div><div className="space-y-0.5">{section.items.map(item=>{const Icon=item.icon;return item.disabled||!item.path?<div key={item.label} className="flex h-8 items-center gap-2 rounded-md px-2 text-[13px] text-muted-foreground/65" aria-disabled="true"><Icon className="size-4"/><span className="flex-1">{item.label}</span><span className="rounded border px-1 text-[10px]">Soon</span></div>:<NavLink key={item.path} to={item.path} onClick={onMobileClose} className={({isActive})=>cn("flex h-8 items-center gap-2 rounded-md px-2 text-[13px] text-muted-foreground transition-colors hover:bg-accent hover:text-foreground focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/20",isActive&&"bg-accent font-medium text-foreground")}><Icon className="size-4"/>{item.label}</NavLink>})}</div></div>)}</nav>
    <Button type="button" variant="ghost" className="w-full justify-start text-muted-foreground" onClick={()=>onOpenSettings("general")}><Settings/>Settings</Button></aside>;
  return <><div className="sticky top-0 hidden h-dvh w-[232px] border-r lg:block">{content}</div>{mobileOpen&&<div className="fixed inset-0 z-40 lg:hidden"><button className="absolute inset-0 bg-black/25" onClick={onMobileClose} aria-label="Close navigation overlay"/><div className="absolute inset-y-0 left-0 w-[min(300px,85vw)] border-r shadow-xl">{content}</div></div>}</>;
}
