import { AlertCircle, ChevronDown, ChevronUp, Copy, Info, Pencil, RefreshCw, Trash2 } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ReferenceLine, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ChartContainer, ChartTooltip, ChartTooltipContent } from "@/components/ui/chart";
import { Skeleton } from "@/components/ui/skeleton";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import type { AnalyticsResponse, DashboardCard, DashboardFilters } from "@/types/api";
import { cn } from "@/lib/utils";

const COLORS = ["#2563eb", "#0d9488", "#9333ea", "#ea580c", "#db2777", "#4f46e5", "#65a30d", "#0891b2", "#b45309", "#475569"];
/** Board grid: small occupies one lane, medium two, and full the entire four-lane row. */
export function cardWidthClass(width: DashboardCard["width"]) { return width === "small" ? "xl:col-span-1" : width === "medium" ? "xl:col-span-2" : "xl:col-span-4"; }

export function DashboardCardView({ card, response, loading, error, filters, editable, draggable, onDragStart, onDragOver, onDrop, onRetry, onEdit, onDuplicate, onDelete, onMove, onDrilldown }: { card: DashboardCard; response?: AnalyticsResponse; loading?: boolean; error?: string; filters: DashboardFilters; editable?: boolean; draggable?: boolean; onDragStart?: () => void; onDragOver?: () => void; onDrop?: () => void; onRetry?: () => void; onEdit?: () => void; onDuplicate?: () => void; onDelete?: () => void; onMove?: (delta: number) => void; onDrilldown?: () => void }) {
  return <Card draggable={draggable} onDragStart={onDragStart} onDragOver={(event) => { if (draggable) event.preventDefault(); onDragOver?.(); }} onDrop={(event) => { if (draggable) event.preventDefault(); onDrop?.(); }} className={cn("min-w-0 transition-shadow", cardWidthClass(card.width), draggable && "cursor-grab active:cursor-grabbing hover:shadow-md")}>
    <CardHeader className="flex-row items-start justify-between gap-3"><div className="min-w-0"><CardTitle className="flex items-center gap-1.5"><span className="truncate">{card.title}</span>{response && <TooltipProvider><Tooltip><TooltipTrigger aria-label="Metric definition"><Info className="size-3.5 text-muted-foreground" /></TooltipTrigger><TooltipContent className="max-w-72">{response.metadata.definition}</TooltipContent></Tooltip></TooltipProvider>}</CardTitle><div className="mt-1 truncate text-xs text-muted-foreground">{filters.segmentId ? "Segment applied · " : ""}{filters.excludedEventNames.length ? `${filters.excludedEventNames.length} events excluded · ` : ""}{filters.granularity} · UTC</div></div>
      {editable && <div className="flex shrink-0"><Button variant="ghost" size="icon" aria-label="Move card earlier" onClick={() => onMove?.(-1)}><ChevronUp /></Button><Button variant="ghost" size="icon" aria-label="Move card later" onClick={() => onMove?.(1)}><ChevronDown /></Button><Button variant="ghost" size="icon" aria-label="Edit card" onClick={onEdit}><Pencil /></Button><Button variant="ghost" size="icon" aria-label="Duplicate card" onClick={onDuplicate}><Copy /></Button><Button variant="ghost" size="icon" aria-label="Delete card" onClick={onDelete}><Trash2 /></Button></div>}
    </CardHeader>
    <CardContent>{loading ? <div className="space-y-3"><Skeleton className="h-8 w-32" /><Skeleton className="h-48 w-full" /></div> : error ? <div className="flex min-h-40 flex-col items-center justify-center gap-3 text-center"><AlertCircle className="size-6 text-destructive" /><p className="text-sm text-muted-foreground">{error}</p><Button size="sm" variant="outline" onClick={onRetry}><RefreshCw />Retry</Button></div> : response ? <ResultView card={card} response={response} /> : <div className="flex min-h-40 items-center justify-center text-sm text-muted-foreground">No data yet.</div>}</CardContent>
    {response && <div className="border-t px-5 py-2 text-[11px] text-muted-foreground">Last refreshed {new Date(response.metadata.dataFreshness).toLocaleTimeString()} · {response.metadata.timezone}</div>}
    {response && onDrilldown && response.metadata.drilldown.length > 0 && <div className="border-t px-5 py-2 text-right"><Button size="sm" variant="ghost" onClick={onDrilldown}>View details</Button></div>}
  </Card>;
}

function ResultView({ card, response }: { card: DashboardCard; response: AnalyticsResponse }) {
  const result = response.result;
  if (result.kind === "scalar") return <div className="flex min-h-40 flex-wrap items-center gap-8">{result.values.map((v) => { const visualization = card.configuration.kind === "metric" ? card.configuration.visualization : "total"; const shown = visualization === "recent" ? v.recentValue : v.value; return <div key={v.seriesKey}><div className="text-4xl font-semibold tracking-tight">{formatValue(shown, card)}</div>{visualization === "previous_period" && <div className={cn("mt-2 text-sm", (v.deltaPercent ?? 0) >= 0 ? "text-emerald-600" : "text-red-600")}>{v.deltaPercent === null ? "No prior value" : `${v.deltaPercent >= 0 ? "+" : ""}${v.deltaPercent}% vs previous`}</div>}</div>; })}</div>;
  if (result.kind === "breakdown") {
    if (!result.rows.length) return <Empty />;
    if (card.configuration.kind === "metric" && card.configuration.visualization === "table") return <table className="w-full text-sm"><thead><tr><th className="pb-2 text-left">Group</th><th className="pb-2 text-right">Value</th></tr></thead><tbody>{result.rows.map((r) => <tr key={r.key} className="border-t"><td className="py-2">{r.label}</td><td className="py-2 text-right font-mono">{r.value.toLocaleString()}</td></tr>)}</tbody></table>;
    return <ChartContainer config={{ value: { label: "Value", color: COLORS[0] } }}><BarChart data={result.rows} layout={card.configuration.kind === "metric" && card.configuration.visualization === "horizontal_bars" ? "vertical" : "horizontal"}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey={card.configuration.kind === "metric" && card.configuration.visualization === "horizontal_bars" ? "value" : "label"} type={card.configuration.kind === "metric" && card.configuration.visualization === "horizontal_bars" ? "number" : "category"} tickLine={false} /><YAxis dataKey="label" type={card.configuration.kind === "metric" && card.configuration.visualization === "horizontal_bars" ? "category" : "number"} hide={card.configuration.kind === "metric" && card.configuration.visualization !== "horizontal_bars"} width={100} /><ChartTooltip content={<ChartTooltipContent />} /><Bar dataKey="value" fill={COLORS[0]} radius={4} /></BarChart></ChartContainer>;
  }
  if (result.kind === "timeseries") {
    if (!result.buckets.some((b) => Object.values(b.values).some(Boolean))) return <Empty />;
    const data = result.buckets.map((b) => ({ label: b.label, ...b.values })); const config = Object.fromEntries(result.series.map((s, i) => [s.key, { label: s.label, color: COLORS[i] }]));
    if (card.configuration.kind === "metric" && card.configuration.visualization === "table") return <table className="w-full text-sm"><thead><tr><th className="text-left">Period</th>{result.series.map((s) => <th key={s.key} className="text-right">{s.label}</th>)}</tr></thead><tbody>{data.map((row) => <tr key={row.label as string} className="border-t"><td className="py-2">{row.label as string}</td>{result.series.map((s) => <td key={s.key} className="text-right font-mono">{Number((row as Record<string, string | number>)[s.key] ?? 0).toLocaleString()}</td>)}</tr>)}</tbody></table>;
    const bars = card.configuration.kind === "metric" && ["bars", "stacked_bars"].includes(card.configuration.visualization);
    return <ChartContainer config={config}>{bars ? <BarChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" tickLine={false} /><YAxis tickLine={false} /><ChartTooltip content={<ChartTooltipContent />} />{result.series.map((s, i) => <Bar key={s.key} dataKey={s.key} fill={COLORS[i]} stackId={card.configuration.kind === "metric" && card.configuration.visualization === "stacked_bars" ? "value" : undefined} radius={3} />)}{card.configuration.kind === "metric" && card.configuration.target && <ReferenceLine y={card.configuration.target.value} stroke="#dc2626" strokeDasharray="4 4" />}</BarChart> : <LineChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" tickLine={false} /><YAxis tickLine={false} /><ChartTooltip content={<ChartTooltipContent />} />{result.series.map((s, i) => <Line key={s.key} type="monotone" dataKey={s.key} stroke={COLORS[i]} strokeWidth={2} dot={false} />)}{card.configuration.kind === "metric" && card.configuration.target && <ReferenceLine y={card.configuration.target.value} stroke="#dc2626" strokeDasharray="4 4" />}</LineChart>}</ChartContainer>;
  }
  if (result.kind === "funnel") { const max = result.steps[0]?.users || 1; return <div className="space-y-3">{result.steps.map((step) => <div key={step.index}><div className="mb-1 flex justify-between text-xs"><span>{step.label}</span><span>{step.users.toLocaleString()} · {step.conversionFromStart}%</span></div><div className="flex h-8 overflow-hidden rounded bg-muted" style={{ width: `${Math.max(12, step.users / max * 100)}%` }}><div className="bg-blue-600" style={{ width: `${step.users ? (step.users - step.droppedBeforeNext) / step.users * 100 : 0}%` }} /><div className="bg-blue-200" style={{ flex: 1 }} /></div></div>)}</div>; }
  if (!result.rows.length) return <Empty />;
  if (card.configuration.kind === "retention" && card.configuration.visualization === "trend") { const keys = result.rows.map((r) => r.key); return <ChartContainer config={Object.fromEntries(keys.map((k, i) => [k, { label: result.rows[i].label, color: COLORS[i] }]))}><LineChart data={result.trend.map((p) => ({ label: p.label, ...p.values }))}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" /><YAxis domain={[0, 100]} /><ChartTooltip content={<ChartTooltipContent />} />{keys.map((k, i) => <Line key={k} dataKey={k} stroke={COLORS[i]} strokeWidth={2} dot={false} />)}</LineChart></ChartContainer>; }
  return <div className="overflow-x-auto"><table className="w-full min-w-max text-xs"><thead><tr><th className="p-2 text-left">Cohort</th><th className="p-2 text-right">Size</th>{result.rows[0].cells.map((c) => <th key={c.offset} className="p-2 text-right">{c.label}</th>)}</tr></thead><tbody>{result.rows.map((row) => <tr key={row.key} className="border-t"><td className="p-2 font-medium">{row.label}{row.smallCohort && <span className="ml-1 text-amber-600" title="Small cohort">⚠</span>}</td><td className="p-2 text-right">{row.size}</td>{row.cells.map((cell) => <td key={cell.offset} className={cn("p-2 text-right", cell.incomplete && "opacity-45")} style={{ backgroundColor: `rgba(37,99,235,${Math.max(.05, cell.percentage / 125)})` }}>{cell.percentage}%</td>)}</tr>)}</tbody></table>{result.rows.some((r) => r.currentSegmentComparison) && <p className="mt-2 text-xs text-muted-foreground">Current Segment comparison; membership is not historical.</p>}</div>;
}
function formatValue(value: number, card: DashboardCard) { if (card.configuration.kind === "metric" && (card.configuration.metricId.includes("rate") || card.configuration.metricId === "users.stickiness")) return `${value}%`; if (card.configuration.kind === "metric" && card.configuration.metricId === "sessions.observed_duration") return `${Math.round(value / 1000)}s`; return value.toLocaleString(); }
function Empty() { return <div className="flex min-h-40 items-center justify-center text-sm text-muted-foreground">No matching analytics in this range.</div>; }
