import { act, fireEvent, render, screen, within } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { createRef } from "react";
import { GrapesWidgetBuilder, type GrapesWidgetBuilderHandle } from "./GrapesWidgetBuilder";

const harness = vi.hoisted(() => ({ handlers: new Map<string, (...args: any[]) => void>(), init: vi.fn(), destroy: vi.fn(), dirty: 0 }));
vi.mock("grapesjs", () => ({ default: { init: harness.init } }));

function fakeEditor() {
  let html = '<section class="movecues-widget"><h2 data-movecues-content="heading">Hello</h2><p data-movecues-content="body" class="movecues-widget__body">World</p></section>'; let device = "Desktop"; let activeProjectData: Record<string, unknown> = { pages: [] }; const widgetElement = document.createElement("section"); const childElement = document.createElement("p"); widgetElement.appendChild(childElement); const canvasDocument = document.implementation.createHTMLDocument(); const canvasStyle = canvasDocument.createElement("style"); canvasStyle.dataset.builderCss = ""; canvasDocument.head.appendChild(canvasStyle); const frameElement = document.createElement("iframe"); const rootClasses = ["movecues-widget"]; const childClasses = ["movecues-widget__body"]; const rootValues = new Map<string, unknown>(); const childValues = new Map<string, unknown>(); let childStyle: Record<string, string> = {}; let childDragMode = ""; let childTagName = "p"; let childAttributes: Record<string, string> = {}; let childTraits: unknown[] = []; let selectedComponent: any;
  canvasDocument.body.appendChild(widgetElement); Object.defineProperties(widgetElement, { offsetWidth: { configurable: true, value: 600 }, offsetHeight: { configurable: true, value: 320 }, clientWidth: { configurable: true, value: 600 }, clientHeight: { configurable: true, value: 320 } }); Object.defineProperties(childElement, { offsetLeft: { configurable: true, value: 30 }, offsetTop: { configurable: true, value: 40 }, offsetWidth: { configurable: true, value: 220 }, offsetHeight: { configurable: true, value: 60 } }); widgetElement.getBoundingClientRect = () => ({ left: 100, top: 50, width: widgetElement.offsetWidth, height: widgetElement.offsetHeight, right: 100 + widgetElement.offsetWidth, bottom: 50 + widgetElement.offsetHeight, x: 100, y: 50, toJSON: () => ({}) }); childElement.getBoundingClientRect = () => ({ left: 130, top: 90, width: childElement.offsetWidth, height: childElement.offsetHeight, right: 130 + childElement.offsetWidth, bottom: 90 + childElement.offsetHeight, x: 130, y: 90, toJSON: () => ({}) });
  const addClasses = (current: string[], next: string | string[]) => { for (const name of Array.isArray(next) ? next : next.split(/\s+/)) if (name && !current.includes(name)) current.push(name); }; const removeClasses = (current: string[], next: string | string[]) => { for (const name of Array.isArray(next) ? next : next.split(/\s+/)) { const index = current.indexOf(name); if (index >= 0) current.splice(index, 1); } };
  const child: any = { getId: () => "i-child", getClasses: () => [...childClasses], addClass: (next: string | string[]) => addClasses(childClasses, next), removeClass: (next: string | string[]) => removeClasses(childClasses, next), get: (key: string) => key === "tagName" ? childTagName : childValues.get(key), set: (key: string, next: unknown) => childValues.set(key, next), getEl: () => childElement, getStyle: () => ({ ...childStyle }), setStyle: (next: Record<string, string>) => { childStyle = { ...next }; }, setDragMode: (mode = "") => { childDragMode = mode; }, parent: () => root, is: () => false, index: () => 0, move: vi.fn(), getAttributes: () => ({ ...childAttributes }), getTraits: () => childTraits };
  const root: any = { getId: () => "i-root", getClasses: () => [...rootClasses], addClass: (next: string | string[]) => addClasses(rootClasses, next), removeClass: (next: string | string[]) => removeClasses(rootClasses, next), get: (key: string) => key === "tagName" ? "section" : key === "type" ? "movecues-widget-root" : rootValues.get(key), set: (key: string, next: unknown) => rootValues.set(key, next), getEl: () => widgetElement, getStyle: () => ({}), components: () => ({ length: 1, forEach: (callback: (component: any) => void) => callback(child) }), getAttributes: () => ({}), getTraits: () => [], parent: () => null };
  selectedComponent = child;
  const rules = new Map<string, any>(); const serializeCss = () => [...rules.values()].map(rule => `${rule.selector}{${Object.entries(rule.style).map(([key, value]) => `${key}:${value}`).join(";")}}`).join(""); const renderCss = () => { canvasStyle.textContent = serializeCss(); }; const makeRule = (selector: string, style: Record<string, string>) => { const rule = { selector, style: { ...style }, getStyle: () => ({ ...rule.style }), selectorsToString: () => selector }; return rule; }; const installCss = (value: string) => { rules.clear(); for (const match of value.matchAll(/([^{}]+)\{([^{}]*)\}/g)) { const selector = match[1].trim(); const style = Object.fromEntries(match[2].split(";").map(entry => entry.split(":" , 2).map(part => part.trim())).filter(parts => parts.length === 2 && parts[0])); rules.set(selector, makeRule(selector, style)); } renderCss(); }; const Css = { setRule: vi.fn((selector: string, style: Record<string, string>) => { const rule = makeRule(selector, style); rules.set(selector, rule); renderCss(); return rule; }), getRule: vi.fn((selector: string) => rules.get(selector)), getRules: vi.fn(() => [...rules.values()]), remove: vi.fn((target: string | { selector: string }) => { const removed = rules.delete(typeof target === "string" ? target : target.selector); renderCss(); return removed; }), clear: vi.fn(() => { rules.clear(); renderCss(); }) };
  const editor: any = {
    DomComponents: { addType: vi.fn() }, Css, StyleManager: { select: vi.fn(), getSelected: vi.fn() }, UndoManager: { undo: vi.fn(), redo: vi.fn(), start: vi.fn(), stop: vi.fn(), isTracking: vi.fn(() => true) }, Canvas: { setZoom: vi.fn(), setCoords: vi.fn(), getDocument: vi.fn(() => canvasDocument), getFrameEl: vi.fn(() => frameElement) }, refresh: vi.fn(),
    on: vi.fn((name: string, handler: (...args: any[]) => void) => { const previous = harness.handlers.get(name); harness.handlers.set(name, previous ? (...args: any[]) => { previous(...args); handler(...args); } : handler); }), onReady: vi.fn((handler: () => void) => window.setTimeout(handler, 0)), destroy: harness.destroy,
    getHtml: vi.fn(() => html.replace(/class="movecues-widget[^"]*"/, `class="${rootClasses.join(" ")}"`).replace(/class="movecues-widget__body[^"]*"/, `class="${childClasses.join(" ")}"`)), getCss: vi.fn((options?: { avoidProtected?: boolean }) => options?.avoidProtected ? serializeCss() : `*{box-sizing:border-box}body{margin:0}${serializeCss()}`), getProjectData: vi.fn(() => activeProjectData), getDirtyCount: vi.fn(() => harness.dirty), clearDirtyCount: vi.fn(), setDevice: vi.fn((name: string) => { device = name; }), getDevice: vi.fn(() => device), getSelected: vi.fn(() => selectedComponent), select: vi.fn((component: any) => { selectedComponent = component; }), setComponents: vi.fn((value: string) => { html = value; const parsed = new DOMParser().parseFromString(value, "text/html"); const parsedRoot = parsed.querySelector(".movecues-widget"); const parsedChild = parsed.querySelector(".movecues-widget__body, p, h2"); rootClasses.splice(0, rootClasses.length, ...(parsedRoot ? [...parsedRoot.classList] : ["movecues-widget"])); childClasses.splice(0, childClasses.length, ...(parsedChild ? [...parsedChild.classList] : [])); }), setStyle: vi.fn((value: string) => installCss(value)), getWrapper: vi.fn(() => ({ find: vi.fn((selector: string) => selector === ".movecues-widget" ? [root] : []), components: vi.fn(() => ({ length: 0 })) })), __root: root, __child: child, __rules: rules, __childStyle: (next?: Record<string, string>) => { if (next) childStyle = { ...next }; return { ...childStyle }; }, __configureChild: (next: { classes?: string[]; tagName?: string; attributes?: Record<string, string>; traits?: unknown[] }) => { if (next.classes) childClasses.splice(0, childClasses.length, ...next.classes); if (next.tagName) childTagName = next.tagName; if (next.attributes) childAttributes = { ...next.attributes }; if (next.traits) childTraits = [...next.traits]; }, __canvasStyle: canvasStyle, __childDragMode: () => childDragMode,
  };
  harness.init.mockImplementation((config: any) => { config.plugins?.forEach((plugin: any) => plugin(editor)); if (config.components) editor.setComponents(config.components); if (config.style) editor.setStyle(config.style); activeProjectData = { pages: [{ id: "page-1", component: { components: [{}] } }], styles: [] }; return editor; }); return editor;
}

describe("GrapesWidgetBuilder", () => {
  afterEach(() => { harness.handlers.clear(); harness.init.mockReset(); harness.destroy.mockReset(); harness.dirty = 0; vi.useRealTimers(); });
  it("initializes once, mounts custom managers, bootstraps once, and destroys cleanly", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); const onChange = vi.fn(); const props = { experienceKey: "exp:v1", widgetType: "modal" as const, content: { heading: "Hello", body: "World" }, design: { width: "md" as const, theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" as const } }, onChange, onPrimaryActionChange: vi.fn(), onSizeChange: vi.fn() };
    const view = render(<GrapesWidgetBuilder {...props} />); await act(async () => { await vi.dynamicImportSettled(); vi.runOnlyPendingTimers(); });
    expect(harness.init).toHaveBeenCalledTimes(1); const config = harness.init.mock.calls[0][0]; expect(config.storageManager).toBe(false); expect(config.selectorManager.componentFirst).toBe(true); expect(config.blockManager.appendTo).toBeInstanceOf(HTMLElement); expect(config.traitManager.appendTo).toBeInstanceOf(HTMLElement); expect(config.styleManager.appendTo).toBeInstanceOf(HTMLElement); expect(config.blockManager.appendTo.closest("[role=tabpanel]")?.id).toBe("movecues-builder-blocks-panel"); expect(config.traitManager.appendTo.closest("[role=tabpanel]")?.id).toBe("movecues-builder-properties-panel"); expect(config.styleManager.appendTo.closest("[role=tabpanel]")?.id).toBe("movecues-builder-properties-panel"); expect(editor.setComponents).toHaveBeenCalledWith(expect.stringContaining('data-movecues-widget-type="modal"')); expect(onChange).toHaveBeenCalledTimes(1); expect(onChange.mock.calls[0][0].builder.projectData).toEqual({}); expect(editor.getProjectData).not.toHaveBeenCalled();
    fireEvent.click(screen.getByRole("button", { name: "Undo" })); fireEvent.click(screen.getByRole("button", { name: "Redo" })); expect(editor.UndoManager.undo).toHaveBeenCalledTimes(1); expect(editor.UndoManager.redo).toHaveBeenCalledTimes(1);
    view.rerender(<GrapesWidgetBuilder {...props} content={{ heading: "Changed externally", body: "World" }} />); expect(harness.init).toHaveBeenCalledTimes(1); view.unmount(); expect(harness.destroy).toHaveBeenCalledTimes(1);
  });

  it("registers the additive content, embed, and guide blocks without changing existing block ids", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); render(<GrapesWidgetBuilder experienceKey="exp:new-blocks" widgetType="modal" content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={vi.fn()} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />);
    await act(async () => { await vi.dynamicImportSettled(); vi.runOnlyPendingTimers(); });
    const config = harness.init.mock.calls[0][0]; const blocks = config.blockManager.blocks as Array<{ id: string; label: string; media: string; category: string; content: unknown }>; const ids = blocks.map(block => block.id);
    expect(ids).toEqual(["free-area", "container", "row", "columns", "heading", "text", "image", "icon", "divider", "video", "badge", "avatar", "list", "spacer", "button", "secondary-button", "embed", "progress", "close"]);
    expect(blocks.every(block => block.media.includes("<svg") && block.media.includes('aria-hidden="true"'))).toBe(true);
    expect(blocks.filter(block => ["video", "badge", "avatar", "list"].includes(block.id)).every(block => block.category === "Content")).toBe(true);
    expect(blocks.find(block => block.id === "embed")).toMatchObject({ label: "Embed", category: "Embed" });
    expect(blocks.filter(block => ["progress", "close"].includes(block.id)).every(block => block.category === "Guide")).toBe(true);
    expect(config.parser.optionsHtml).toEqual({ allowScripts: false, allowUnsafeAttr: false, allowUnsafeAttrValue: false });
    const definitions = new Map<string, any>(editor.DomComponents.addType.mock.calls.map((call: unknown[]) => [String(call[0]), call[1]]));
    expect([...definitions.keys()]).toEqual(expect.arrayContaining(["movecues-video", "movecues-avatar-image", "movecues-embed-frame"]));
    expect(definitions.get("movecues-video").model.defaults.traits.map((trait: { name: string }) => trait.name)).toEqual(["src", "autoplay", "muted", "loop", "controls"]);
    expect(definitions.get("movecues-avatar-image").model.defaults.traits.map((trait: { name: string }) => trait.name)).toEqual(["src", "alt"]);
    expect(definitions.get("movecues-embed-frame").model.defaults.traits.map((trait: { name: string }) => trait.name)).toEqual(["src", "title"]);
  });

  it("exports inserted blocks with scoped baseline CSS while preserving existing CSS", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); const onChange = vi.fn(); const css = ".movecues-widget{background:#123456}"; render(<GrapesWidgetBuilder experienceKey="exp:insert-blocks" widgetType="modal" value={{ version: 1, projectData: {}, html: '<section class="movecues-widget"></section>', css }} content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={onChange} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />);
    await act(async () => { await vi.dynamicImportSettled(); vi.runOnlyPendingTimers(); }); onChange.mockClear();
    const blockClasses = ["movecues-widget__video", "movecues-widget__badge", "movecues-widget__avatar", "movecues-widget__list", "movecues-widget__embed", "movecues-widget__progress", "movecues-widget__close"];
    act(() => { for (const className of blockClasses) harness.handlers.get("component:add")?.({ ...editor.__child, getAttributes: () => ({}), getClasses: () => [className] }); });
    editor.setComponents('<section class="movecues-widget"><div class="movecues-widget__video"><video controls playsinline muted src="https://cdn.test/demo.mp4"><source src=""></video></div><span class="movecues-widget__badge">Updated</span><div class="movecues-widget__avatar"><img class="movecues-widget__avatar-image" src="https://cdn.test/avatar.png" alt="Profile"></div><ul class="movecues-widget__list"><li>First item</li></ul><div class="movecues-widget__embed"><iframe class="movecues-widget__embed-frame" src="https://example.test" title="Embedded content" loading="lazy"></iframe></div><div class="movecues-widget__progress" aria-label="Progress"><span class="movecues-widget__progress-dot movecues-widget__progress-dot--active"></span></div><button class="movecues-widget__close" type="button" aria-label="Close">&times;</button></section>');
    harness.dirty = 1; act(() => { harness.handlers.get("update")?.(); vi.advanceTimersByTime(400); });
    expect(onChange).toHaveBeenCalledTimes(1); const exported = onChange.mock.calls[0][0].builder;
    for (const className of blockClasses) expect(exported.html).toContain(className);
    expect(exported.html).toContain("Updated"); expect(exported.css).toContain(".movecues-widget{background:#123456}");
    for (const className of blockClasses) expect(exported.css).toContain(`.movecues-widget .${className}`);
    act(() => harness.handlers.get("component:selected")?.(editor.__child)); expect(screen.getByRole("tab", { name: "Properties" })).toHaveAttribute("aria-selected", "true");
  });

  it("reloads saved new block HTML and CSS from the canonical fields", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); const onChange = vi.fn(); const html = '<section class="movecues-widget"><video class="movecues-widget__video" src="https://cdn.test/demo.mp4" controls="" muted=""></video><iframe class="movecues-widget__embed-frame" src="https://example.test" title="Example" loading="lazy"></iframe><ul class="movecues-widget__list"><li>Saved item</li></ul></section>'; const css = ".movecues-widget{color:#111}.movecues-widget .movecues-widget__video{width:100%}";
    render(<GrapesWidgetBuilder experienceKey="exp:reload-new-blocks" widgetType="modal" value={{ version: 1, projectData: { stale: true }, html, css }} content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={onChange} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />);
    await act(async () => { await vi.dynamicImportSettled(); vi.runOnlyPendingTimers(); }); const config = harness.init.mock.calls[0][0];
    expect(config.components).toContain('<video class="movecues-widget__video" src="https://cdn.test/demo.mp4" controls="" muted="">'); expect(config.components).toContain("Saved item"); expect(config.style).toBe(css); expect(editor.getHtml()).toContain("Saved item"); expect(editor.getCss({ avoidProtected: true })).toBe(css); expect(onChange).not.toHaveBeenCalled();
  });

  it("lets GrapesJS test survey component types against text nodes safely", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); render(<GrapesWidgetBuilder experienceKey="exp:survey" widgetType="survey" content={{ heading: "Survey", body: "Tell us more" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={vi.fn()} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />);
    await act(async () => { await vi.dynamicImportSettled(); vi.runOnlyPendingTimers(); });
    const definitions: Array<{ isComponent: (node: Node) => unknown }> = editor.DomComponents.addType.mock.calls.map((call: unknown[]) => call[1] as { isComponent: (node: Node) => unknown });
    expect(() => definitions.forEach(definition => definition.isComponent(document.createTextNode("survey copy")))).not.toThrow();
    const button = document.createElement("button"); button.dataset.movecuesSurveyAction = "next"; const buttonType = editor.DomComponents.addType.mock.calls.find((call: unknown[]) => call[0] === "movecues-button")?.[1]; expect(buttonType.isComponent(button)).toEqual({ type: "movecues-button" }); expect(buttonType.model.defaults).toMatchObject({ removable: true, copyable: false });
    const controls = document.createElement("div"); controls.dataset.movecuesSurveyControls = "builder"; const controlsType = editor.DomComponents.addType.mock.calls.find((call: unknown[]) => call[0] === "movecues-survey-controls")?.[1]; expect(controlsType.isComponent(controls)).toEqual({ type: "movecues-survey-controls" }); expect(controlsType.model.defaults).toMatchObject({ removable: false, copyable: false });
    const root = document.createElement("section"); root.className = "movecues-widget"; const rootType = editor.DomComponents.addType.mock.calls.find((call: unknown[]) => call[0] === "movecues-widget-root")?.[1]; expect(rootType.isComponent(root)).toEqual({ type: "movecues-widget-root" }); expect(rootType.model.defaults).toMatchObject({ removable: false, copyable: false });
  });

  it("exits the loading state without autosaving if GrapesJS never becomes ready", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); editor.onReady.mockImplementation(() => undefined); render(<GrapesWidgetBuilder experienceKey="exp:ready-fallback" widgetType="modal" content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={vi.fn()} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />);
    await act(async () => { await vi.dynamicImportSettled(); vi.advanceTimersByTime(5000); vi.runAllTimers(); }); expect(screen.queryByText("Loading builder…")).not.toBeInTheDocument(); expect(screen.getAllByText(/Autosave is disabled/)).not.toHaveLength(0);
  });

  it("never exports the temporary empty project emitted while GrapesJS is hydrating", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); const onChange = vi.fn(); const html = '<section class="movecues-widget"><h2 class="movecues-widget__heading">Safe</h2><button class="movecues-widget__button">Continue</button></section>'; const css = ".movecues-widget{background:#123456}.movecues-widget .movecues-widget__button{color:white}"; const projectData = { pages: [{ id: "page-1", frames: [{ component: { type: "wrapper", components: [{ tagName: "section", classes: ["movecues-widget"] }] } }] }], styles: [{ selectors: ["movecues-widget"], style: { background: "#123456" } }], html, css }; let projectReady = false;
    editor.getProjectData.mockImplementation(() => projectReady ? projectData : { pages: [], styles: [] }); editor.onReady.mockImplementation((handler: () => void) => window.setTimeout(handler, 1000)); render(<GrapesWidgetBuilder experienceKey="exp:hydration-race" widgetType="modal" value={{ version: 1, projectData, html, css }} content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={onChange} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />); await act(async () => { await vi.dynamicImportSettled(); }); onChange.mockClear();
    act(() => { editor.setComponents('<section class="movecues-widget"></section>'); editor.Css.clear(); harness.dirty = 1; harness.handlers.get("component:remove")?.(editor.__child); harness.handlers.get("update")?.(); vi.advanceTimersByTime(500); }); expect(onChange).not.toHaveBeenCalled();
    act(() => { projectReady = true; editor.setComponents(html); editor.setStyle(css); vi.advanceTimersByTime(500); }); await act(async () => { await Promise.resolve(); }); expect(onChange).not.toHaveBeenCalled(); expect(editor.getHtml()).toContain("Continue"); expect(editor.getCss({ avoidProtected: true })).toBe(css);
  });

  it("persists StyleManager changes through one stable scoped CssComposer rule", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); const onChange = vi.fn(); const html = '<section class="movecues-widget"><p class="movecues-widget__body">World</p></section>'; render(<GrapesWidgetBuilder experienceKey="exp:v2" widgetType="banner" value={{ version: 1, projectData: { pages: [] }, html, css: ".movecues-widget{color:#111}" }} content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={onChange} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />);
    await act(async () => { await vi.dynamicImportSettled(); vi.runAllTimers(); }); onChange.mockClear(); act(() => harness.handlers.get("style:property:update")?.()); editor.__childStyle({ "font-size": "32px", color: "red" }); editor.Css.setRule("#i-child", { "font-size": "32px", color: "red" }); act(() => harness.handlers.get("component:styleUpdate")?.(editor.__child)); await act(async () => { await Promise.resolve(); }); act(() => vi.advanceTimersByTime(400)); const styleClass = editor.__child.getClasses().find((name: string) => name.startsWith("movecues-style--")); expect(styleClass).toBeTruthy(); const selector = `.movecues-widget .${styleClass}`; expect(editor.Css.getRule(selector)?.getStyle()).toEqual({ "font-size": "32px", color: "red" }); expect(editor.Css.getRule("#i-child")).toBeUndefined(); expect(onChange).toHaveBeenCalledTimes(1); expect(onChange.mock.calls[0][0].builder.css).toContain(`${selector}{font-size:32px;color:red}`); expect(editor.__canvasStyle.textContent).toContain(`${selector}{font-size:32px;color:red}`);
  });

  it("replaces stale CssComposer rules when applying canonical HTML and CSS from code mode", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); const onChange = vi.fn(); render(<GrapesWidgetBuilder experienceKey="exp:v3" widgetType="toast" value={{ version: 1, projectData: { pages: [] }, html: '<section class="movecues-widget"></section>', css: ".movecues-widget{}" }} content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={onChange} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />);
    await act(async () => { await vi.dynamicImportSettled(); vi.runOnlyPendingTimers(); }); onChange.mockClear(); const canvas = document.querySelector(".movecues-builder-editor"); fireEvent.click(screen.getByRole("button", { name: "Toggle HTML and CSS editor" })); editor.Css.setRule("#i-child", { color: "gray", "font-size": "14px" }); expect(screen.getByLabelText("Builder CSS")).not.toHaveValue(expect.stringContaining("body{")); fireEvent.change(screen.getByLabelText("Builder HTML"), { target: { value: '<section class="movecues-widget"><script>alert(1)</script><h2 class="movecues-widget__heading">Safe</h2></section>' } }); const css = ".movecues-widget{background:#0d132d}.movecues-widget .movecues-widget__heading{color:#fff;font-size:32px}"; fireEvent.change(screen.getByLabelText("Builder CSS"), { target: { value: css } }); fireEvent.click(screen.getByRole("button", { name: "Apply HTML and CSS" })); expect(editor.Css.clear).toHaveBeenCalled(); expect(editor.Css.getRule("#i-child")).toBeUndefined(); expect(editor.Css.getRule(".movecues-widget")?.getStyle()).toEqual({ background: "#0d132d" }); expect(editor.Css.getRule(".movecues-widget .movecues-widget__heading")?.getStyle()).toEqual({ color: "#fff", "font-size": "32px" }); expect(editor.__canvasStyle.textContent).toBe(css); expect(onChange).toHaveBeenCalledTimes(1); expect(onChange.mock.calls[0][0].builder.html).not.toContain("script"); expect(onChange.mock.calls[0][0].builder.css).toBe(css); fireEvent.click(screen.getByRole("button", { name: "Toggle HTML and CSS editor" })); act(() => vi.runOnlyPendingTimers()); expect(document.querySelector(".movecues-builder-editor")).toBe(canvas); expect(harness.init).toHaveBeenCalledTimes(1); expect(editor.refresh).toHaveBeenCalled();
  });

  it("formats HTML and CSS in code mode without applying the draft", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); const onChange = vi.fn(); render(<GrapesWidgetBuilder experienceKey="exp:format" widgetType="modal" value={{ version: 1, projectData: {}, html: '<section class="movecues-widget"></section>', css: ".movecues-widget{}" }} content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={onChange} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />);
    await act(async () => { await vi.dynamicImportSettled(); vi.runOnlyPendingTimers(); }); onChange.mockClear(); fireEvent.click(screen.getByRole("button", { name: "Toggle HTML and CSS editor" })); fireEvent.change(screen.getByLabelText("Builder HTML"), { target: { value: '<section class="movecues-widget"><h2>Safe</h2></section>' } }); fireEvent.change(screen.getByLabelText("Builder CSS"), { target: { value: ".movecues-widget{background:#0d132d;color:#fff}" } }); fireEvent.click(screen.getByRole("button", { name: "Format HTML and CSS" }));
    expect(screen.getByLabelText("Builder HTML")).toHaveValue('<section class="movecues-widget">\n  <h2>Safe</h2>\n</section>'); expect(screen.getByLabelText("Builder CSS")).toHaveValue(".movecues-widget {\n  background:#0d132d;\n  color:#fff\n}"); expect(editor.setComponents).not.toHaveBeenCalledTimes(2); expect(onChange).not.toHaveBeenCalled();
  });

  it("loads canonical runtime HTML and CSS instead of hydrating stale projectData", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); const onChange = vi.fn(); const html = '<section class="movecues-widget"><h2 class="movecues-widget__heading">Canonical</h2></section>'; const css = ".movecues-widget{background:#0d132d}.movecues-widget .movecues-widget__heading{color:#fff;font-size:32px}"; const projectData = { pages: [{ id: "page-1", frames: [{ id: "frame-1", component: { type: "wrapper", components: [{ type: "text", content: "Stale" }] } }] }], html: '<section class="movecues-widget"><h2 class="movecues-widget__heading">Stale</h2></section>', css: ".movecues-widget{background:gray}.movecues-widget .movecues-free-item--persisted{left:140px;top:92px;width:280px}" };
    render(<GrapesWidgetBuilder experienceKey="exp:reload" widgetType="modal" value={{ version: 1, projectData, html, css }} content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={onChange} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />); await act(async () => { await vi.dynamicImportSettled(); vi.runOnlyPendingTimers(); }); const config = harness.init.mock.calls[0][0]; expect(config).not.toHaveProperty("projectData"); expect(config.components).toBe(html); expect(config.style).toBe(css); expect(editor.getHtml()).toContain("Canonical"); expect(editor.getHtml()).not.toContain("Stale"); expect(editor.getCss({ avoidProtected: true })).toBe(css); expect(editor.Css.getRule(".movecues-widget .movecues-free-item--persisted")).toBeUndefined(); expect(editor.setComponents).toHaveBeenCalledTimes(1); expect(editor.Css.clear).not.toHaveBeenCalled(); expect(editor.setStyle).toHaveBeenCalledTimes(1); expect(onChange).not.toHaveBeenCalled();
  });

  it("loads runtime CSS directly when projectData has components but no styles", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); const html = '<section class="movecues-widget"><h2 class="movecues-widget__heading">Fallback CSS</h2></section>'; const css = ".movecues-widget{background:#123456}"; const projectData = { pages: [{ id: "page-1", frames: [{ id: "frame-1", component: { type: "wrapper", components: [{ type: "text", content: "Preserved" }] } }] }] };
    render(<GrapesWidgetBuilder experienceKey="exp:css-fallback" widgetType="modal" value={{ version: 1, projectData, html, css }} content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={vi.fn()} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />); await act(async () => { await vi.dynamicImportSettled(); vi.runOnlyPendingTimers(); }); expect(harness.init.mock.calls[0][0]).not.toHaveProperty("projectData"); expect(editor.setComponents).toHaveBeenCalledWith(html); expect(editor.getCss({ avoidProtected: true })).toBe(css); expect(editor.setStyle).toHaveBeenCalledWith(css);
  });

  it("falls back to saved HTML and CSS when projectData is unusable", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); const html = '<section class="movecues-widget"><h2 class="movecues-widget__heading">Fallback</h2></section>'; const css = ".movecues-widget{background:#123456}";
    render(<GrapesWidgetBuilder experienceKey="exp:fallback" widgetType="modal" value={{ version: 1, projectData: { pages: [] }, html, css }} content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={vi.fn()} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />); await act(async () => { await vi.dynamicImportSettled(); vi.runOnlyPendingTimers(); }); expect(harness.init.mock.calls[0][0]).not.toHaveProperty("projectData"); expect(editor.getHtml()).toContain("Fallback"); expect(editor.getCss({ avoidProtected: true })).toBe(css); expect(editor.Css.clear).not.toHaveBeenCalled();
  });

  it("flushes a pending canvas mutation without waiting for the debounce", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); const onChange = vi.fn(); const ref = createRef<GrapesWidgetBuilderHandle>(); render(<GrapesWidgetBuilder ref={ref} experienceKey="exp:v4" widgetType="modal" value={{ version: 1, projectData: { original: true }, html: '<section class="movecues-widget"></section>', css: ".movecues-widget{}" }} content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={onChange} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />);
    await act(async () => { await vi.dynamicImportSettled(); vi.runOnlyPendingTimers(); }); editor.setComponents('<section class="movecues-widget"><button>New button</button></section>'); harness.dirty = 1; act(() => harness.handlers.get("update")?.()); act(() => ref.current?.flush()); expect(onChange).toHaveBeenCalledTimes(1);
  });

  it("never serializes projectData from text or component mutation paths", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); const onChange = vi.fn(); const projectData = { retained: "compatibility-metadata" };
    editor.getProjectData.mockImplementation(() => { throw new Error("getProjectData must not run during editing"); });
    render(<GrapesWidgetBuilder experienceKey="exp:no-project-data-loop" widgetType="modal" value={{ version: 1, projectData, html: '<section class="movecues-widget"><p class="movecues-widget__body">Before</p></section>', css: ".movecues-widget{color:#111}" }} content={{ heading: "Hello", body: "Before" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={onChange} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />);
    await act(async () => { await vi.dynamicImportSettled(); vi.runOnlyPendingTimers(); }); onChange.mockClear();
    editor.setComponents('<section class="movecues-widget"><p class="movecues-widget__body">After</p></section>'); harness.dirty = 1;
    act(() => { harness.handlers.get("component:remove")?.(editor.__child); harness.handlers.get("component:add")?.(editor.__child); harness.handlers.get("rte:disable")?.(); harness.handlers.get("update")?.(); vi.advanceTimersByTime(400); });
    expect(editor.getProjectData).not.toHaveBeenCalled(); expect(onChange).toHaveBeenCalledTimes(1); expect(onChange.mock.calls[0][0].builder).toMatchObject({ projectData, html: expect.stringContaining("After") });
  });

  it("repairs an empty CSS export from the last styled state before saving", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); const onChange = vi.fn(); render(<GrapesWidgetBuilder experienceKey="exp:style-guard" widgetType="modal" value={{ version: 1, projectData: { pages: [] }, html: '<section class="movecues-widget"></section>', css: ".movecues-widget{background:#123456}" }} content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={onChange} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />);
    await act(async () => { await vi.dynamicImportSettled(); vi.runOnlyPendingTimers(); }); onChange.mockClear(); editor.Css.clear(); harness.dirty = 1; act(() => harness.handlers.get("update")?.()); act(() => vi.advanceTimersByTime(400)); expect(onChange).toHaveBeenCalledTimes(1); expect(onChange.mock.calls[0][0].builder.css).toBe(".movecues-widget{background:#123456}"); expect(screen.queryByText(/empty stylesheet/)).not.toBeInTheDocument();
  });

  it("uses a neutral authoring surface and fits the widget inside the visible workspace", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); render(<GrapesWidgetBuilder experienceKey="exp:v5" widgetType="modal" value={{ version: 1, projectData: { pages: [] }, html: '<section class="movecues-widget"></section>', css: ".movecues-widget{}" }} content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={vi.fn()} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />);
    const canvas = document.querySelector<HTMLElement>(".movecues-builder-editor");
    expect(canvas).not.toBeNull();
    Object.defineProperties(canvas!, { clientWidth: { configurable: true, value: 720 }, clientHeight: { configurable: true, value: 560 } });
    await act(async () => { await vi.dynamicImportSettled(); vi.runAllTimers(); });
    const devices = harness.init.mock.calls[0][0].deviceManager.devices;
    expect(devices.map((entry: { width: string; height: string }) => [entry.width, entry.height])).toEqual([["1200px", "900px"], ["1200px", "900px"], ["1200px", "900px"]]);
    expect(harness.init.mock.calls[0][0].canvasCss).toContain("min-width:1200px"); expect(harness.init.mock.calls[0][0].canvasCss).toContain("min-height:900px"); expect(harness.init.mock.calls[0][0].canvasCss).toContain("button{border:0;border-radius:7px;padding:8px 12px");
    expect(editor.Canvas.setZoom).toHaveBeenCalledWith(100);
    expect(editor.Canvas.setCoords).toHaveBeenCalledWith(-240, 0);
    const widget = editor.getWrapper().find(".movecues-widget")[0].getEl();
    Object.defineProperties(widget, { offsetWidth: { configurable: true, value: 900 }, offsetHeight: { configurable: true, value: 700 } });
    fireEvent.click(screen.getByRole("button", { name: /Mobile/ }));
    act(() => vi.runAllTimers());
    expect(editor.setDevice).toHaveBeenLastCalledWith("Mobile");
    expect(editor.Canvas.setZoom).toHaveBeenLastCalledWith(expect.closeTo(66.29, 1));
    expect(editor.Canvas.setCoords).toHaveBeenLastCalledWith(expect.closeTo(-37.71, 1), 0);
  });

  it("pans with the Hand tool, preserves the viewport on updates, and resets it only with Fit", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); const onChange = vi.fn(); render(<GrapesWidgetBuilder experienceKey="exp:viewport" widgetType="modal" value={{ version: 1, projectData: { pages: [] }, html: '<section class="movecues-widget"></section>', css: ".movecues-widget{}" }} content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={onChange} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />);
    const editorElement = document.querySelector<HTMLElement>(".movecues-builder-editor")!; Object.defineProperties(editorElement, { clientWidth: { configurable: true, value: 720 }, clientHeight: { configurable: true, value: 560 } });
    await act(async () => { await vi.dynamicImportSettled(); vi.runAllTimers(); });
    fireEvent.click(screen.getByRole("button", { name: "Zoom in" })); expect(editor.Canvas.setZoom).toHaveBeenLastCalledWith(110); expect(screen.getByLabelText("Zoom percentage")).toHaveTextContent("110%");
    fireEvent.click(screen.getByRole("button", { name: "Hand tool" })); const panLayer = document.querySelector<HTMLElement>(".movecues-builder-pan-layer")!; expect(panLayer).toHaveClass("movecues-builder-pan-layer--active");
    fireEvent.pointerDown(panLayer, { button: 0, pointerId: 7, clientX: 100, clientY: 100 }); fireEvent.pointerMove(panLayer, { pointerId: 7, clientX: 140, clientY: 160 }); fireEvent.pointerUp(panLayer, { pointerId: 7 });
    expect(editor.Canvas.setCoords).toHaveBeenLastCalledWith(-260, 32);
    editor.Canvas.setZoom.mockClear(); editor.Canvas.setCoords.mockClear(); harness.dirty = 1; act(() => harness.handlers.get("update")?.());
    expect(editor.Canvas.setZoom).not.toHaveBeenCalled(); expect(editor.Canvas.setCoords).not.toHaveBeenCalled();
    fireEvent.click(screen.getByRole("button", { name: "Fit" })); act(() => vi.runAllTimers()); expect(editor.Canvas.setZoom).toHaveBeenLastCalledWith(100); expect(editor.Canvas.setCoords).toHaveBeenLastCalledWith(-240, 0); expect(screen.getByLabelText("Zoom percentage")).toHaveTextContent("100%");
  });

  it("zooms toward the cursor, ignores normal wheel events, and clamps toolbar zoom", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); render(<GrapesWidgetBuilder experienceKey="exp:zoom" widgetType="modal" value={{ version: 1, projectData: { pages: [] }, html: '<section class="movecues-widget"></section>', css: ".movecues-widget{}" }} content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={vi.fn()} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />);
    const editorElement = document.querySelector<HTMLElement>(".movecues-builder-editor")!; Object.defineProperties(editorElement, { clientWidth: { configurable: true, value: 720 }, clientHeight: { configurable: true, value: 560 } });
    await act(async () => { await vi.dynamicImportSettled(); vi.runAllTimers(); }); const viewport = document.querySelector<HTMLElement>(".movecues-builder-canvas")!;
    editor.Canvas.setZoom.mockClear(); editor.Canvas.setCoords.mockClear(); fireEvent.wheel(viewport, { deltaY: -100, clientX: 100, clientY: 80 }); expect(editor.Canvas.setZoom).not.toHaveBeenCalled();
    fireEvent.wheel(viewport, { deltaY: -100, clientX: 100, clientY: 80, ctrlKey: true }); expect(editor.Canvas.setZoom).toHaveBeenLastCalledWith(expect.closeTo(122.14, 2)); expect(editor.Canvas.setCoords).toHaveBeenLastCalledWith(expect.closeTo(-315.28, 2), expect.closeTo(-17.71, 2));
    for (let index = 0; index < 20; index += 1) fireEvent.click(screen.getByRole("button", { name: "Zoom in" })); expect(editor.Canvas.setZoom).toHaveBeenLastCalledWith(200); expect(screen.getByLabelText("Zoom percentage")).toHaveTextContent("200%");
    for (let index = 0; index < 30; index += 1) fireEvent.click(screen.getByRole("button", { name: "Zoom out" })); expect(editor.Canvas.setZoom).toHaveBeenLastCalledWith(25); expect(screen.getByLabelText("Zoom percentage")).toHaveTextContent("25%");
  }, 10000);

  it("uses Space as a temporary Hand tool without intercepting editable fields", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); render(<GrapesWidgetBuilder experienceKey="exp:space" widgetType="modal" content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={vi.fn()} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />);
    await act(async () => { await vi.dynamicImportSettled(); vi.runAllTimers(); }); const panLayer = document.querySelector<HTMLElement>(".movecues-builder-pan-layer")!;
    act(() => window.dispatchEvent(new KeyboardEvent("keydown", { code: "Space" }))); expect(panLayer).toHaveClass("movecues-builder-pan-layer--active"); fireEvent.pointerDown(panLayer, { button: 0, pointerId: 3, clientX: 20, clientY: 30 }); fireEvent.pointerMove(panLayer, { pointerId: 3, clientX: 70, clientY: 90 }); expect(document.querySelector(".movecues-builder-canvas")).toHaveClass("movecues-builder-canvas--panning"); act(() => window.dispatchEvent(new KeyboardEvent("keyup", { code: "Space" }))); expect(panLayer).not.toHaveClass("movecues-builder-pan-layer--active"); expect(document.querySelector(".movecues-builder-canvas")).not.toHaveClass("movecues-builder-canvas--panning");
    act(() => harness.handlers.get("component:selected")?.(editor.__root)); const widthInput = screen.getByLabelText("Widget width"); fireEvent.keyDown(widthInput, { code: "Space" }); expect(panLayer).not.toHaveClass("movecues-builder-pan-layer--active");
    const editable = editor.Canvas.getDocument().createElement("div"); editable.setAttribute("contenteditable", "true"); editor.Canvas.getDocument().body.appendChild(editable); act(() => editable.dispatchEvent(new KeyboardEvent("keydown", { code: "Space", bubbles: true }))); expect(panLayer).not.toHaveClass("movecues-builder-pan-layer--active");
    fireEvent.click(screen.getByRole("button", { name: "Toggle HTML and CSS editor" })); fireEvent.keyDown(screen.getByLabelText("Builder HTML"), { code: "Space" }); expect(panLayer).not.toHaveClass("movecues-builder-pan-layer--active");
  });

  it("registers the Free Area block without exposing the old global layout toggle", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); render(<GrapesWidgetBuilder experienceKey="exp:free-area-block" widgetType="modal" content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={vi.fn()} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />); await act(async () => { await vi.dynamicImportSettled(); vi.runAllTimers(); }); const config = harness.init.mock.calls[0][0]; expect(config.blockManager.blocks).toEqual(expect.arrayContaining([expect.objectContaining({ id: "free-area", label: "Free Area", category: "Layout" })])); expect(editor.DomComponents.addType).toHaveBeenCalledWith("movecues-free-area", expect.any(Object)); expect(screen.queryByRole("group", { name: "Layout mode" })).not.toBeInTheDocument(); expect(screen.queryByRole("button", { name: "Free" })).not.toBeInTheDocument();
  });

  it("clamps size input and explains the active widget limit", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); const onSizeChange = vi.fn(); render(<GrapesWidgetBuilder experienceKey="exp:v6" widgetType="toast" content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={vi.fn()} onPrimaryActionChange={vi.fn()} onSizeChange={onSizeChange} />);
    await act(async () => { await vi.dynamicImportSettled(); vi.runAllTimers(); });
    act(() => harness.handlers.get("component:selected")?.(editor.__root)); const width = screen.getByLabelText("Widget width"); expect(width).toHaveValue(380); fireEvent.change(width, { target: { value: "500" } }); expect(editor.Canvas.getDocument().head.querySelector("style[data-movecues-size-envelope]")?.textContent).toContain("width:500px!important"); expect(onSizeChange).not.toHaveBeenCalled(); fireEvent.change(width, { target: { value: "900" } }); fireEvent.blur(width);
    expect(width).toHaveValue(520); expect(screen.getByText("Maximum width for Toast is 520px.")).toBeInTheDocument(); expect(onSizeChange).toHaveBeenCalledWith({ width: { mode: "fixed", value: 520 }, height: { mode: "auto" } });
  });

  it("keeps manager targets mounted while switching sidebar tabs and opens Properties on selection", async () => {
    vi.useFakeTimers(); fakeEditor(); render(<GrapesWidgetBuilder experienceKey="exp:v7" widgetType="modal" content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={vi.fn()} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />);
    await act(async () => { await vi.dynamicImportSettled(); vi.runAllTimers(); });
    const config = harness.init.mock.calls[0][0]; const managerTargets = [config.blockManager.appendTo, config.traitManager.appendTo, config.styleManager.appendTo] as HTMLElement[];
    const blocksTab = screen.getByRole("tab", { name: "Blocks" }); const propertiesTab = screen.getByRole("tab", { name: "Properties" });
    expect(blocksTab).toHaveAttribute("aria-selected", "true"); expect(propertiesTab).toHaveAttribute("aria-selected", "false");
    fireEvent.click(propertiesTab); expect(propertiesTab).toHaveAttribute("aria-selected", "true"); expect(managerTargets.every(target => target.isConnected)).toBe(true);
    fireEvent.click(blocksTab); act(() => harness.handlers.get("component:selected")?.({ getAttributes: () => ({}) }));
    expect(propertiesTab).toHaveAttribute("aria-selected", "true");
  });

  it("shows widget Interaction before styles and updates the existing primary action without reinitializing", async () => {
    vi.useFakeTimers(); fakeEditor(); const onPrimaryActionChange = vi.fn(); const props = { experienceKey: "exp:interaction", widgetType: "modal" as const, interactionContext: "widget" as const, content: { heading: "Hello", body: "World", primaryAction: { label: "Launch", type: "open_url" as const, url: "https://movecues.com" } }, design: { width: "md" as const, theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" as const } }, onChange: vi.fn(), onPrimaryActionChange, onSizeChange: vi.fn() };
    const view = render(<GrapesWidgetBuilder {...props} />); await act(async () => { await vi.dynamicImportSettled(); vi.runAllTimers(); });
    const config = harness.init.mock.calls[0][0]; const primary = { getAttributes: () => ({ "data-movecues-action-id": "primary" }), getClasses: () => [] };
    act(() => harness.handlers.get("component:selected")?.(primary));
    expect(screen.getByRole("tab", { name: "Properties" })).toHaveAttribute("aria-selected", "true"); expect(screen.getByRole("heading", { name: "Interaction" })).toBeInTheDocument();
    const inspector = screen.getByRole("heading", { name: "Interaction" }).parentElement!; expect(config.traitManager.appendTo.compareDocumentPosition(inspector) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy(); expect(inspector.compareDocumentPosition(config.styleManager.appendTo) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();
    expect(screen.getByLabelText("On click")).toHaveValue("open_url"); expect(screen.getByLabelText("URL")).toHaveValue("https://movecues.com");
    fireEvent.change(screen.getByLabelText("On click"), { target: { value: "track_event" } }); expect(onPrimaryActionChange).toHaveBeenLastCalledWith({ label: "Launch", type: "track_event", eventName: "experience_action" });
    fireEvent.change(screen.getByLabelText("On click"), { target: { value: "dismiss" } }); expect(onPrimaryActionChange).toHaveBeenLastCalledWith({ label: "Launch", type: "dismiss" });
    view.rerender(<GrapesWidgetBuilder {...props} content={{ ...props.content, primaryAction: { label: "Launch", type: "track_event", eventName: "launched" } }} />); expect(screen.getByLabelText("Event name")).toHaveValue("launched"); expect(harness.init).toHaveBeenCalledTimes(1);
  });

  it("keeps guide actions constrained and exposes survey actions through normal button Interaction", async () => {
    vi.useFakeTimers(); fakeEditor(); const onPrimaryActionChange = vi.fn(); const view = render(<GrapesWidgetBuilder experienceKey="exp:constrained-interactions" widgetType="anchored_card" interactionContext="guide" content={{ heading: "Guide", body: "Step", primaryAction: { label: "Continue", type: "next_step" } }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={vi.fn()} onPrimaryActionChange={onPrimaryActionChange} onSizeChange={vi.fn()} />);
    await act(async () => { await vi.dynamicImportSettled(); vi.runAllTimers(); }); const selected = (attributes: Record<string, string>) => ({ getAttributes: () => attributes, getClasses: () => [] });
    act(() => harness.handlers.get("component:selected")?.(selected({ "data-movecues-action-id": "primary" }))); const guideSelect = screen.getByLabelText("On click"); expect(guideSelect).toHaveValue("next_step"); expect(guideSelect.querySelectorAll("option")).toHaveLength(1);
    act(() => harness.handlers.get("component:selected")?.(selected({ "data-movecues-action-id": "secondary" }))); expect(screen.getByText("Dismiss experience")).toBeInTheDocument(); expect(screen.queryByLabelText("On click")).not.toBeInTheDocument();
    view.rerender(<GrapesWidgetBuilder experienceKey="exp:constrained-interactions" widgetType="survey" interactionContext="survey" content={{ heading: "Survey", body: "Step" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={vi.fn()} onPrimaryActionChange={onPrimaryActionChange} onSizeChange={vi.fn()} />);
    act(() => harness.handlers.get("component:selected")?.(selected({ "data-movecues-survey-action": "back" }))); const surveySelect = screen.getByLabelText("On click"); expect(surveySelect).toHaveValue("back"); expect(surveySelect).toHaveTextContent("Survey: Back"); expect(surveySelect).toHaveTextContent("Survey: Next"); expect(surveySelect).toHaveTextContent("Survey: Submit");
    act(() => harness.handlers.get("component:selected")?.(selected({ "data-movecues-survey-action": "next" }))); expect(screen.getByLabelText("On click")).toHaveValue("next");
    act(() => harness.handlers.get("component:selected")?.(selected({ "data-movecues-survey-action": "submit" }))); expect(screen.getByLabelText("On click")).toHaveValue("submit"); expect(onPrimaryActionChange).not.toHaveBeenCalled();
    act(() => harness.handlers.get("component:selected")?.(selected({}))); expect(screen.queryByRole("heading", { name: "Interaction" })).not.toBeInTheDocument();
    const nestedChild = { ...selected({ role: "img" }), parent: () => selected({ "data-movecues-action-id": "primary" }) }; act(() => harness.handlers.get("component:selected")?.(nestedChild)); expect(screen.queryByRole("heading", { name: "Interaction" })).not.toBeInTheDocument(); expect(harness.init).toHaveBeenCalledTimes(1); view.unmount();
  });

  it("persists a normal survey Button's configured action in canonical component attributes", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); render(<GrapesWidgetBuilder experienceKey="exp:survey-button-action" widgetType="survey" interactionContext="survey" content={{ heading: "Survey", body: "Step" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={vi.fn()} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />); await act(async () => { await vi.dynamicImportSettled(); vi.runAllTimers(); });
    let attributes: Record<string, string> = { "data-movecues-action-id": "primary" }; const button = { getAttributes: () => attributes, getClasses: () => ["movecues-widget__button"], setAttributes: vi.fn((next: Record<string, string>) => { attributes = next; }) }; editor.getSelected.mockReturnValue(button);
    act(() => harness.handlers.get("component:selected")?.(button)); expect(screen.getByLabelText("On click")).toHaveValue("dismiss"); fireEvent.change(screen.getByLabelText("On click"), { target: { value: "next" } });
    expect(button.setAttributes).toHaveBeenCalledWith({ "data-movecues-survey-action": "next" }); expect(attributes).toEqual({ "data-movecues-survey-action": "next" }); expect(harness.init).toHaveBeenCalledTimes(1);
  });

  it("clamps visual root resizing through the existing size callback without recreating the editor", async () => {
    vi.useFakeTimers(); fakeEditor(); const onSizeChange = vi.fn(); render(<GrapesWidgetBuilder experienceKey="exp:v8" widgetType="modal" content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={vi.fn()} onPrimaryActionChange={vi.fn()} onSizeChange={onSizeChange} />);
    await act(async () => { await vi.dynamicImportSettled(); vi.runAllTimers(); });
    const updateStyle = vi.fn(); const root = { getClasses: () => ["movecues-widget"] };
    act(() => harness.handlers.get("component:resize:update")?.({ component: root, rect: { w: 1400, h: 1200 }, style: { width: "1400px", height: "1200px" }, partial: false, updateStyle }));
    expect(updateStyle).toHaveBeenCalledWith({ width: "960px", height: "900px" }); expect(onSizeChange).toHaveBeenCalledWith({ width: { mode: "fixed", value: 960 }, height: { mode: "fixed", value: 900 } }); expect(harness.init).toHaveBeenCalledTimes(1);
  });

  it("shows root-only widget settings, breadcrumbs, and the collapsed existing StyleManager", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); render(<GrapesWidgetBuilder experienceKey="exp:context" widgetType="modal" content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={vi.fn()} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />);
    await act(async () => { await vi.dynamicImportSettled(); vi.runAllTimers(); }); const config = harness.init.mock.calls[0][0];
    expect(screen.queryByRole("heading", { name: "Widget size" })).not.toBeInTheDocument();
    act(() => harness.handlers.get("component:selected")?.(editor.__root)); expect(screen.getByRole("heading", { name: "Widget size" })).toBeInTheDocument();
    act(() => harness.handlers.get("component:selected")?.(editor.__child)); expect(screen.queryByRole("heading", { name: "Widget size" })).not.toBeInTheDocument(); expect(screen.getByRole("heading", { name: "Typography" })).toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: "Widget" })); expect(editor.select).toHaveBeenCalledWith(editor.__root);
    const advanced = screen.getByText("Advanced styles").closest("details")!; expect(advanced).not.toHaveAttribute("open"); fireEvent.click(screen.getByText("Advanced styles")); expect(advanced).toHaveAttribute("open"); expect(advanced).toContainElement(config.styleManager.appendTo);
  });

  it("writes text alignment, block alignment, and width modes through one canonical class rule", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); const onChange = vi.fn(); render(<GrapesWidgetBuilder experienceKey="exp:text-inspector" widgetType="modal" value={{ version: 1, projectData: {}, html: '<section class="movecues-widget"><p class="movecues-widget__body">World</p></section>', css: ".movecues-widget{color:#111}" }} content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={onChange} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />);
    await act(async () => { await vi.dynamicImportSettled(); vi.runAllTimers(); }); onChange.mockClear(); act(() => harness.handlers.get("component:selected")?.(editor.__child));
    fireEvent.click(within(screen.getByRole("group", { name: "Alignment" })).getByRole("button", { name: "Center" }));
    fireEvent.click(within(screen.getByRole("group", { name: "Block alignment" })).getByRole("button", { name: "Center" }));
    fireEvent.click(within(screen.getByRole("group", { name: "Width" })).getByRole("button", { name: "Hug" }));
    let styleClass = editor.__child.getClasses().find((name: string) => name.startsWith("movecues-style--")); let selector = `.movecues-widget .${styleClass}`;
    expect(editor.Css.getRule(selector)?.getStyle()).toMatchObject({ "text-align": "center", "margin-left": "auto", "margin-right": "auto", width: "fit-content" });
    fireEvent.click(within(screen.getByRole("group", { name: "Width" })).getByRole("button", { name: "Fill" })); expect(editor.Css.getRule(selector)?.getStyle().width).toBe("100%");
    fireEvent.click(within(screen.getByRole("group", { name: "Width" })).getByRole("button", { name: "Fixed" })); fireEvent.change(screen.getByLabelText("Fixed width"), { target: { value: "420" } }); expect(editor.Css.getRule(selector)?.getStyle().width).toBe("420px"); expect(editor.Css.getRule(selector)?.getStyle().position).toBeUndefined();
    act(() => vi.advanceTimersByTime(400)); expect(onChange).toHaveBeenCalledTimes(1); expect(onChange.mock.calls[0][0].builder.css).toContain("text-align:center"); expect(onChange.mock.calls[0][0].builder.css).toContain("width:420px"); expect(onChange.mock.calls[0][0].builder.css).toContain(".movecues-widget{color:#111}");
  });

  it("maps container direction, gap, content position, and padding to canonical flex CSS", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); render(<GrapesWidgetBuilder experienceKey="exp:layout-inspector" widgetType="modal" content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={vi.fn()} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />);
    await act(async () => { await vi.dynamicImportSettled(); vi.runAllTimers(); }); editor.__configureChild({ classes: ["movecues-widget__container"], tagName: "div" }); act(() => harness.handlers.get("component:selected")?.(editor.__child));
    fireEvent.click(within(screen.getByRole("group", { name: "Direction" })).getByRole("button", { name: "Horizontal" }));
    fireEvent.change(screen.getByLabelText("Space between items"), { target: { value: "16" } });
    fireEvent.click(screen.getByRole("button", { name: "Content position bottom right" }));
    fireEvent.change(screen.getByLabelText("Padding all sides"), { target: { value: "24" } }); fireEvent.click(screen.getByRole("button", { name: "Edit sides" })); fireEvent.change(screen.getByLabelText("Top"), { target: { value: "12" } });
    const styleClass = editor.__child.getClasses().find((name: string) => name.startsWith("movecues-style--")); const rule = editor.Css.getRule(`.movecues-widget .${styleClass}`)?.getStyle();
    expect(rule).toMatchObject({ display: "flex", "flex-direction": "row", gap: "16px", "justify-content": "flex-end", "align-items": "flex-end", "padding-top": "12px", "padding-right": "24px", "padding-bottom": "24px", "padding-left": "24px" }); expect(rule.position).toBeUndefined();
  });

  it("refreshes simplified controls after an Advanced StyleManager change", async () => {
    vi.useFakeTimers(); const editor = fakeEditor(); render(<GrapesWidgetBuilder experienceKey="exp:style-sync" widgetType="modal" content={{ heading: "Hello", body: "World" }} design={{ width: "md", theme: { background: "#fff", foreground: "#111", primary: "#2563eb", borderRadius: "md" } }} onChange={vi.fn()} onPrimaryActionChange={vi.fn()} onSizeChange={vi.fn()} />);
    await act(async () => { await vi.dynamicImportSettled(); vi.runAllTimers(); }); act(() => harness.handlers.get("component:selected")?.(editor.__child));
    fireEvent.click(within(screen.getByRole("group", { name: "Alignment" })).getByRole("button", { name: "Center" })); const styleClass = editor.__child.getClasses().find((name: string) => name.startsWith("movecues-style--")); editor.Css.setRule(`.movecues-widget .${styleClass}`, { "text-align": "right" });
    act(() => harness.handlers.get("style:property:update")?.()); await act(async () => { await Promise.resolve(); }); expect(within(screen.getByRole("group", { name: "Alignment" })).getByRole("button", { name: "Right" })).toHaveAttribute("aria-pressed", "true");
  });
});
