import { Fragment, useEffect, useMemo, useState } from "react";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import { AlertTriangle } from "lucide-react";
import { CartesianGrid, Line, LineChart, XAxis, YAxis } from "recharts";
import { useWorkspace } from "../../auth/WorkspaceContext";
import { PageHeader } from "../../components/PageHeader";
import { AnalyticsMetricCard } from "@/components/analytics/AnalyticsMetricCard";
import { EmptyState } from "../../components/EmptyState";
import { DateRangePicker } from "../../components/DateRangePicker";
import { resolveDateRange, type DateRangePreset } from "../../lib/dateRange";
import { formatRelativeTime, formatTimestamp } from "../../lib/format";
import { Button, Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, Skeleton } from "@movecues/ui";
import { ChartContainer, ChartTooltip, ChartTooltipContent } from "@/components/ui/chart";
import { DataTableFrame, ErrorNotice, LoadingRows, dataTableClass } from "@/components/PageSurface";
import { chartAxisTick, chartMargin, getResponsiveDateAxisProps } from "@/lib/chartFormatting";
import { cn } from "@movecues/ui";
import * as funnelsApi from "../../api/funnels";
import * as segmentsApi from "../../api/segments";
import type { Funnel, FunnelAnalysis, FunnelStepResult, FunnelStepUser, Segment, SegmentDefinition, SegmentFunnelCohortCondition, SegmentFunnelCohortDateRange } from "../../types/api";

const STEP_USERS_PAGE_SIZE = 25;
const WINDOWS = [{ value: 60, label: "1 hour" }, { value: 24 * 60, label: "24 hours" }, { value: 3 * 24 * 60, label: "3 days" }, { value: 7 * 24 * 60, label: "7 days" }, { value: 14 * 24 * 60, label: "14 days" }, { value: 30 * 24 * 60, label: "30 days" }, { value: 90 * 24 * 60, label: "90 days" }];
type PerformanceTab = "conversion" | "trend";
type CohortTarget = { step: FunnelStepResult; cohort: "reached" | "dropped_after"; dateRange: SegmentFunnelCohortDateRange };

export const humanize = (value: string) => value.replace(/[_-]+/g, " ").replace(/\b\w/g, char => char.toUpperCase());
const dropRate = (step: FunnelStepResult) => Math.max(0, 100 - step.conversionFromPrevious);

export function FunnelDetailPage() {
  const { currentOrg, currentSite } = useWorkspace(); const { funnelId } = useParams<{ funnelId: string }>(); const navigate = useNavigate(); const [searchParams, setSearchParams] = useSearchParams();
  const preset = (searchParams.get("range") as DateRangePreset | null) ?? "30d"; const customSince = searchParams.get("since") ?? undefined; const customUntil = searchParams.get("until") ?? undefined; const segmentId = searchParams.get("segmentId") ?? "";
  const range = useMemo(() => resolveDateRange(preset, customSince, customUntil), [preset, customSince, customUntil]);
  const [funnel, setFunnel] = useState<Funnel | null>(null); const [analysis, setAnalysis] = useState<FunnelAnalysis | null>(null); const [segments, setSegments] = useState<Segment[]>([]);
  const [error, setError] = useState<string | null>(null); const [deleting, setDeleting] = useState(false); const [openStepIndex, setOpenStepIndex] = useState<number | null>(null); const [tab, setTab] = useState<PerformanceTab>("conversion"); const [cohortTarget, setCohortTarget] = useState<CohortTarget | null>(null); const [creatingSegment, setCreatingSegment] = useState(false);
  const windowMinutes = Number(searchParams.get("window")) || funnel?.conversionWindowMinutes || 7 * 24 * 60;

  function updateParams(changes: Record<string, string | undefined>) { const next = new URLSearchParams(searchParams); for (const [key, value] of Object.entries(changes)) value ? next.set(key, value) : next.delete(key); setSearchParams(next, { replace: true }); }
  function updateRange(nextPreset: DateRangePreset, nextSince?: string, nextUntil?: string) { updateParams({ range: nextPreset, since: nextSince, until: nextUntil }); }
  useEffect(() => { if (!currentOrg || !currentSite || !funnelId) return; setFunnel(null); setError(null); funnelsApi.getFunnel(currentOrg.orgId, currentSite.id, funnelId).then(setFunnel).catch(() => setError("Couldn't load this funnel.")); }, [currentOrg, currentSite, funnelId]);
  useEffect(() => { if (currentOrg && currentSite) void segmentsApi.listSegments(currentOrg.orgId, currentSite.id, { limit: 100 }).then(res => setSegments(res.segments)); }, [currentOrg, currentSite]);
  useEffect(() => { if (!currentOrg || !currentSite || !funnelId || !range) return; setAnalysis(null); setOpenStepIndex(null); funnelsApi.analyzeFunnel(currentOrg.orgId, currentSite.id, funnelId, range, { segmentId: segmentId || undefined, conversionWindowMinutes: windowMinutes }).then(setAnalysis).catch(() => setError("Couldn't analyze this funnel.")); }, [currentOrg, currentSite, funnelId, range?.since, range?.until, segmentId, windowMinutes]);
  async function handleDelete() { if (!currentOrg || !currentSite || !funnelId || !window.confirm("Delete this funnel? This cannot be undone.")) return; setDeleting(true); try { await funnelsApi.deleteFunnel(currentOrg.orgId, currentSite.id, funnelId); navigate("/observe/funnels"); } catch { setError("Couldn't delete this funnel."); setDeleting(false); } }
  async function createCohortSegment(name: string) {
    if (!currentOrg || !currentSite || !funnel || !cohortTarget) return;
    const funnelCohort: SegmentFunnelCohortCondition = { type: "funnel_cohort", funnelId: funnel.id, stepIndex: cohortTarget.step.index, cohort: cohortTarget.cohort, conversionWindowMinutes: windowMinutes, dateRange: cohortTarget.dateRange };
    const selectedDefinition = segmentId ? segments.find((segment) => segment.id === segmentId)?.definition : undefined;
    const definition: SegmentDefinition = selectedDefinition ? { logic: "and", conditions: [selectedDefinition, funnelCohort] } : { logic: "and", conditions: [funnelCohort] };
    setCreatingSegment(true);
    try { const created = await segmentsApi.createSegment(currentOrg.orgId, currentSite.id, { name, definition }); navigate(`/segments/${created.id}`); } catch { setError("Couldn't create this segment."); setCreatingSegment(false); }
  }
  const cohortDateRange = range ? dateRangeForSegment(preset, range) : null;

  if (error) return <><PageHeader section="Observe" title="Funnel" /><ErrorNotice>{error}</ErrorNotice></>;
  if (!funnel) return <><PageHeader section="Observe" title="Funnel" /><Skeleton className="h-72 w-full" /></>;
  return <><PageHeader className="mb-6" section="Observe" title={funnel.name} description={funnel.description ?? undefined} actions={<div className="flex gap-2"><Button variant="outline" onClick={() => navigate(`/observe/funnels/${funnel.id}/edit`)}>Edit</Button><Button variant="ghost" className="text-destructive" onClick={handleDelete} disabled={deleting}>{deleting ? "Deleting…" : "Delete"}</Button></div>} />
    <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><DateRangePicker preset={preset} customSince={customSince} customUntil={customUntil} onChange={updateRange} /><div className="flex flex-wrap items-center gap-2"><label className="text-[12.5px] text-muted-foreground">Complete within:</label><select aria-label="Conversion window" className="h-9 rounded-md border bg-input px-3 text-sm shadow-sm focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/20" value={windowMinutes} onChange={event => updateParams({ window: event.target.value })}>{WINDOWS.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select><label className="ml-1 text-[12.5px] text-muted-foreground">Analyze users:</label><select className="h-9 w-[180px] rounded-md border bg-input px-3 text-sm shadow-sm focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/20" value={segmentId} onChange={event => updateParams({ segmentId: event.target.value || undefined })}><option value="">All users</option>{segments.map(segment => <option key={segment.id} value={segment.id}>{segment.name}</option>)}</select></div></div>
    {!analysis || !range || !cohortDateRange ? <Skeleton className="h-80 w-full" /> : <FunnelResults analysis={analysis} tab={tab} onTabChange={setTab} since={range.since} until={range.until} openStepIndex={openStepIndex} onToggleStep={index => setOpenStepIndex(openStepIndex === index ? null : index)} orgId={currentOrg!.orgId} siteId={currentSite!.id} funnelId={funnel.id} segmentId={segmentId || undefined} windowMinutes={windowMinutes} onCreateCohort={(step, cohort) => setCohortTarget({ step, cohort, dateRange: cohortDateRange })} onOpenUser={user => navigate(user.trackedUserId ? `/users/${user.trackedUserId}` : `/users/anonymous/${user.anonymousId}`)} />}
    <CreateFunnelCohortDialog open={Boolean(cohortTarget)} funnelName={funnel.name} target={cohortTarget} creating={creatingSegment} onClose={() => !creatingSegment && setCohortTarget(null)} onCreate={createCohortSegment} />
  </>;
}

function FunnelResults({ analysis, tab, onTabChange, since, until, openStepIndex, onToggleStep, orgId, siteId, funnelId, segmentId, windowMinutes, onCreateCohort, onOpenUser }: { analysis: FunnelAnalysis; tab: PerformanceTab; onTabChange: (tab: PerformanceTab) => void; since: string; until: string; openStepIndex: number | null; onToggleStep: (index: number) => void; orgId: string; siteId: string; funnelId: string; segmentId?: string; windowMinutes: number; onCreateCohort: (step: FunnelStepResult, cohort: "reached" | "dropped_after") => void; onOpenUser: (user: FunnelStepUser) => void }) {
  if (!analysis.steps.length) return <EmptyState title="This funnel has no steps" description="Edit the funnel to add at least one step." />;
  const largestDrop = findLargestDrop(analysis.steps);
  return <div className="space-y-7"><div className="grid grid-cols-1 gap-3 sm:grid-cols-3"><AnalyticsMetricCard label="Conversion" value={`${analysis.overallConversion}%`} description={`${analysis.convertedUsers.toLocaleString()} of ${analysis.totalUsers.toLocaleString()} users`} /><AnalyticsMetricCard label="Started" value={analysis.totalUsers.toLocaleString()} description="Users who entered this funnel" /><AnalyticsMetricCard label="Completed" value={analysis.convertedUsers.toLocaleString()} description="Users who reached the final step" /></div>
    <section aria-labelledby="funnel-performance"><div className="mb-4 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 id="funnel-performance" className="text-base font-semibold">Funnel performance</h2><p className="mt-1 text-sm text-muted-foreground">Users progress through each step in order.</p></div><div className="flex gap-1 rounded-lg bg-muted/50 p-1" role="tablist"><Tab active={tab === "conversion"} onClick={() => onTabChange("conversion")}>Conversion</Tab><Tab active={tab === "trend"} onClick={() => onTabChange("trend")}>Trend</Tab></div></div>
      {tab === "conversion" ? <><LargestDrop drop={largestDrop} /><SteppedFunnel steps={analysis.steps} onToggleStep={onToggleStep} /><FunnelBreakdown steps={analysis.steps} openStepIndex={openStepIndex} onToggleStep={onToggleStep} orgId={orgId} siteId={siteId} funnelId={funnelId} since={since} until={until} segmentId={segmentId} windowMinutes={windowMinutes} onCreateCohort={onCreateCohort} onOpenUser={onOpenUser} /></> : <TrendChart analysis={analysis} />}
    </section>
  </div>;
}
function Tab({ active, onClick, children }: { active: boolean; onClick: () => void; children: string }) { return <button type="button" role="tab" aria-selected={active} onClick={onClick} className={cn("rounded-md px-3 py-1.5 text-xs font-medium transition-colors", active ? "bg-background text-foreground shadow-sm" : "text-muted-foreground hover:text-foreground")}>{children}</button>; }
function LargestDrop({ drop }: { drop: { from: FunnelStepResult; to: FunnelStepResult; users: number; percent: number } | null }) { return drop ? <div className="mb-4 inline-flex items-center gap-2 rounded-md border border-amber-200 bg-amber-50/60 px-3 py-2 text-xs text-amber-900"><AlertTriangle className="size-3.5 text-amber-600" /><span><strong className="font-semibold">Largest drop</strong><span className="mx-1.5 text-amber-400">·</span>{humanize(drop.from.label)} → {humanize(drop.to.label)}<span className="mx-1.5 text-amber-400">·</span>{drop.percent}% · {drop.users.toLocaleString()} users</span></div> : null; }
function SteppedFunnel({ steps, onToggleStep }: { steps: FunnelStepResult[]; onToggleStep: (index: number) => void }) { const max = steps[0]?.users || 1; return <div className="overflow-x-auto rounded-xl border bg-card p-4"><div className="flex min-w-max items-end gap-6 pb-2">{steps.map((step, index) => { const before = index ? steps[index - 1] : undefined; const lost = before?.droppedBeforeNext ?? 0; const comparisonUsers = before?.users ?? step.users; const height = comparisonUsers === 0 ? 8 : Math.max(32, Math.round(comparisonUsers / max * 166)); return <div key={step.index} className="w-36 shrink-0"><button type="button" onClick={() => onToggleStep(step.index)} title={`${humanize(step.label)}\n${step.users.toLocaleString()} users reached\n${step.conversionFromPrevious}% from previous step\n${step.conversionFromStart}% of starters`} className="group flex h-56 w-full flex-col justify-end text-left"><div className="mb-2 flex min-h-9 items-end justify-between gap-2"><span className="text-lg font-semibold tracking-tight">{step.users.toLocaleString()}</span><span className="text-xs text-muted-foreground">{step.conversionFromStart}%</span></div><div className="relative overflow-hidden rounded-t-md bg-primary/10 transition-colors group-hover:bg-primary/15" style={{ height }}><div className="absolute inset-x-0 bottom-0 bg-primary/85" style={{ height: `${step.conversionFromPrevious}%` }} /></div></button><div className="border-t pt-2"><div className="truncate text-sm font-medium" title={humanize(step.label)}>{humanize(step.label)}</div>{step.eventName && <div className="mt-0.5 truncate text-[11px] text-muted-foreground" title={step.eventName}>{step.eventName}</div>}</div></div>; })}</div></div>; }
function TrendChart({ analysis }: { analysis: FunnelAnalysis }) { if (!analysis.trend.some(point => point.startedUsers)) return <EmptyState title="No data in this range" description="Try a wider date range." />; return <div className="h-[250px]"><ChartContainer className="h-full" config={{ conversion: { label: "Conversion", color: "#4f46e5" } }}>{({ width }) => <LineChart data={analysis.trend} margin={chartMargin}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="currentColor" className="text-muted/70" /><XAxis dataKey="date" tickLine={false} axisLine={false} {...getResponsiveDateAxisProps(analysis.trend.map(point => point.date), width)} /><YAxis domain={[0, 100]} tickLine={false} axisLine={false} tick={chartAxisTick} tickFormatter={value => `${value}%`} width={38} /><ChartTooltip content={<ChartTooltipContent />} /><Line type="monotone" dataKey="conversion" stroke="#4f46e5" strokeWidth={2.25} dot={false} activeDot={{ r: 3, fill: "#4f46e5", strokeWidth: 0 }} /></LineChart>}</ChartContainer></div>; }
function FunnelBreakdown({ steps, openStepIndex, onToggleStep, orgId, siteId, funnelId, since, until, segmentId, windowMinutes, onCreateCohort, onOpenUser }: { steps: FunnelStepResult[]; openStepIndex: number | null; onToggleStep: (index: number) => void; orgId: string; siteId: string; funnelId: string; since: string; until: string; segmentId?: string; windowMinutes: number; onCreateCohort: (step: FunnelStepResult, cohort: "reached" | "dropped_after") => void; onOpenUser: (user: FunnelStepUser) => void }) {
  return <div className="mt-6"><h3 className="mb-3 text-sm font-semibold">Step breakdown</h3><DataTableFrame><table className={dataTableClass}><thead><tr><th>Step</th><th className="text-right">Users</th><th className="text-right">Step conversion</th><th className="text-right">Drop-off</th><th className="text-right">Action</th></tr></thead><tbody>{steps.map((step, index) => { const finalStep = index === steps.length - 1; return <Fragment key={step.index}><tr><td><button type="button" className="text-left font-medium hover:underline" onClick={() => onToggleStep(step.index)}>{humanize(step.label)}{step.eventName && <span className="mt-0.5 block text-xs font-normal text-muted-foreground">{step.eventName}</span>}</button></td><td className="text-right"><button type="button" className="font-mono hover:underline" onClick={() => onToggleStep(step.index)}>{step.users.toLocaleString()}</button></td><td className="text-right font-mono">{index === 0 ? "—" : `${step.conversionFromPrevious}%`}</td><td className="text-right font-mono text-muted-foreground">{index === 0 ? "—" : `${dropRate(step)}% · ${steps[index - 1].droppedBeforeNext.toLocaleString()}`}</td><td className="text-right"><details className="relative inline-block text-left"><summary className="cursor-pointer list-none rounded-md border px-2.5 py-1 text-xs font-medium hover:bg-muted">Create segment</summary><div className="absolute right-0 z-10 mt-1 w-56 rounded-md border bg-popover p-1 shadow-md"><button type="button" className="w-full rounded px-2 py-1.5 text-left text-xs hover:bg-muted" onClick={() => onCreateCohort(step, "reached")}>{finalStep ? "Completed funnel" : "Reached this step"} — {step.users.toLocaleString()}</button>{!finalStep && <button type="button" className="w-full rounded px-2 py-1.5 text-left text-xs hover:bg-muted" onClick={() => onCreateCohort(step, "dropped_after")}>Dropped after this step — {step.droppedBeforeNext.toLocaleString()}</button>}</div></details></td></tr>{openStepIndex === step.index && <tr><td colSpan={5} className="bg-muted/25 p-0"><StepUsersPanel orgId={orgId} siteId={siteId} funnelId={funnelId} stepIndex={step.index} since={since} until={until} segmentId={segmentId} windowMinutes={windowMinutes} onOpenUser={onOpenUser} /></td></tr>}</Fragment>; })}</tbody></table></DataTableFrame></div>;
}
function StepUsersPanel({ orgId, siteId, funnelId, stepIndex, since, until, segmentId, windowMinutes, onOpenUser }: { orgId: string; siteId: string; funnelId: string; stepIndex: number; since: string; until: string; segmentId?: string; windowMinutes: number; onOpenUser: (user: FunnelStepUser) => void }) { const [users, setUsers] = useState<FunnelStepUser[] | null>(null); const [total, setTotal] = useState(0); const [offset, setOffset] = useState(0); useEffect(() => { setUsers(null); funnelsApi.getFunnelStepUsers(orgId, siteId, funnelId, stepIndex, { since, until }, { segmentId, conversionWindowMinutes: windowMinutes, limit: STEP_USERS_PAGE_SIZE, offset }).then(result => { setUsers(result.users); setTotal(result.total); }); }, [orgId, siteId, funnelId, stepIndex, since, until, segmentId, windowMinutes, offset]); return <div className="p-3">{users === null ? <LoadingRows count={2} /> : !users.length ? <EmptyState title="No users reached this step" description="Nobody matched in this date range and filter." /> : <><table className="w-full text-sm"><thead><tr className="text-left text-xs text-muted-foreground"><th className="pb-2">User</th><th className="pb-2">Type</th><th className="pb-2">Last seen</th></tr></thead><tbody>{users.map(user => <tr key={user.trackedUserId ?? user.anonymousId} className="cursor-pointer border-t hover:bg-muted/50" onClick={() => onOpenUser(user)}><td className="py-2 font-mono">{user.identityType === "identified" ? user.externalUserId : user.anonymousId}</td><td className="py-2">{user.identityType === "identified" ? "Identified" : "Anonymous"}</td><td className="py-2 text-muted-foreground" title={user.lastSeenAt ? formatTimestamp(user.lastSeenAt) : undefined}>{user.lastSeenAt ? formatRelativeTime(user.lastSeenAt) : "—"}</td></tr>)}</tbody></table>{total > STEP_USERS_PAGE_SIZE && <div className="mt-3 flex items-center justify-between"><span className="text-xs text-muted-foreground">{offset + 1}–{Math.min(offset + STEP_USERS_PAGE_SIZE, total)} of {total.toLocaleString()}</span><div className="flex gap-2"><Button variant="ghost" size="sm" disabled={!offset} onClick={() => setOffset(Math.max(0, offset - STEP_USERS_PAGE_SIZE))}>Previous</Button><Button variant="ghost" size="sm" disabled={offset + STEP_USERS_PAGE_SIZE >= total} onClick={() => setOffset(offset + STEP_USERS_PAGE_SIZE)}>Next</Button></div></div>}</>}</div>; }
function cohortName(funnelName: string, target: CohortTarget) {
  if (target.cohort === "dropped_after") return `${funnelName} — ${humanize(target.step.label)} drop-offs`;
  return `${funnelName} — ${humanize(target.step.label)} reached`;
}
function CreateFunnelCohortDialog({ open, funnelName, target, creating, onClose, onCreate }: { open: boolean; funnelName: string; target: CohortTarget | null; creating: boolean; onClose: () => void; onCreate: (name: string) => void }) {
  const [name, setName] = useState("");
  useEffect(() => { if (target) setName(cohortName(funnelName, target)); }, [funnelName, target]);
  return <Dialog open={open} onOpenChange={(next) => !next && onClose()}><DialogContent className="max-w-md overflow-hidden p-0"><DialogHeader className="border-b px-5 py-4 pr-12"><DialogTitle className="text-[17px] tracking-[-0.01em]">Create segment</DialogTitle><DialogDescription className="text-[13px] leading-5">{target?.cohort === "dropped_after" ? "Users who reached this step but did not reach the next one within this funnel’s conversion window." : "Users who reached this ordered funnel step within the selected analysis scope."}</DialogDescription></DialogHeader><div className="p-5"><label className="grid gap-1.5 text-[13px] font-medium">Segment name<input aria-label="Segment name" className="h-9 rounded-md border bg-input px-3 text-sm font-normal shadow-[rgba(0,0,0,.05)_0_1px_2px] focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/20" value={name} onChange={(event) => setName(event.target.value)} autoFocus /></label></div><DialogFooter className="border-t px-5 py-3"><Button variant="ghost" onClick={onClose} disabled={creating}>Cancel</Button><Button disabled={creating || !name.trim()} onClick={() => onCreate(name.trim())}>{creating ? "Creating…" : "Create segment"}</Button></DialogFooter></DialogContent></Dialog>;
}
function dateRangeForSegment(preset: DateRangePreset, range: { since: string; until: string }): SegmentFunnelCohortDateRange {
  if (preset === "custom") return { type: "absolute", since: range.since, until: range.until };
  if (preset === "today") return { type: "today" };
  return { type: "relative", days: Number.parseInt(preset, 10) };
}
export function findLargestDrop(steps: FunnelStepResult[]) { const candidates = steps.slice(1).map((step, index) => ({ from: steps[index], to: step, users: steps[index].droppedBeforeNext, percent: dropRate(step) })).filter(drop => drop.users > 0 && drop.from.users > 0); return candidates.reduce<(typeof candidates)[number] | null>((largest, current) => !largest || current.percent > largest.percent ? current : largest, null); }
